### ISSUE TITLE
Smart layout spriting not working

### ISSUE THREAD

**Issue by patocallaghan** [Compass/compass#1024]
Hey,

I've followed the tutorials online but can't seem to get smart layouts in the spriting to work. The sprites are always generated horizontally.

My SCSS is as follows:

``` scss
$icons: sprite-map("interface/ico/icon/*.png");
$icons-layout:smart;
@import "interface/ico/icon/*.png";
```

I then customise my CSS using a whole set of the following rules.

``` scss
[class*="icon-"] {
    position: relative;
    &:before {
        @extend %pseudo-element;
        background: $icons;
    }
}
.icon-newsletter {
    &:before {
        @include sprite-background-position($icons, newsletter);
        @include sprite-dimensions($icons, newsletter);
    }
}
```

I guess the problem is to do with the fact I'm using sprite-maps?

Thanks,
Pat
