### ISSUE TITLE
Way to iterate over sprites in a map

### ISSUE THREAD

**Issue by jakearchibald** [Compass/compass#1046]
Say I wanted more control over the classnames produced for my sprite, I could do something like this

``` scss
$social-icons-map: sprite-map("social-icons/*.png", 
    $spacing: 1px, 
    $layout: horizontal
);

.si {
    width: 48px;
    height: 48px;
    display: inline-block;
    vertical-align: middle;
    background: $social-icons-map no-repeat;
}

@each $sprite in sprites($social-icons-map) {
    .si-#{$sprite} {
        background-position: sprite-position($social-icons-map, $sprite);
    }
}
```

Now I can do `<div class="si si-github">` for the github icon, for example.

The missing ingredient is the sprites($map) function, which returns a list of sprite names for a given map.
