### ISSUE TITLE
Feature Request: combine selectors for multiple use of inline-image.

### ISSUE THREAD

**Issue by jackmoore** [Compass/compass#1096]
Right now if I use the same inline-image multiple times in the stylesheet, each use ends up including the same data URI in the processed CSS.  It would be nice if the selectors were re-written so that a given URI is only present in the stylesheet a single time.

**Comment by Anahkiasen** [comment]
Use SASS placeholders.

**Comment by mirisuzanne** [comment]
There is no good way to automate this. Because code order is meaningful in the cascade, any magic re-arrangement of the code is a bad idea. But we do have offer this feature as an explicit option, so you can do it yourself:

``` scss
%my-inline-img {
  background-image: inline-image('something.png');
}

.first-use { @extend %my-inline-img; }
.second-use { @extend %my-inline-img; }

// result

.first-use, .second-use {
  background-image: /*...data...*/;
}
```
