### ISSUE TITLE
Support prefixed properties in new @supports block

### ISSUE THREAD

**Issue by mirisuzanne** [Compass/compass#1101]
http://dev.opera.com/articles/view/native-css-feature-detection-via-the-supports-rule/

``` css
@supports (display: -webkit-flex) or
          (display: -moz-flex) or
          (display: flex) {
  section {
    display: -webkit-flex;
    display: -moz-flex;
    display: flex;
    /* … */
  }           
}
```
