### ISSUE TITLE
table.striped should apply for both table rules in blueprint typography

### ISSUE THREAD

**Issue by alexhayes** [Compass/compass#1102]
The blueprint _typography.sass defines the following:

``` css
  table.striped tr:nth-child(even) td,
  table tr.even            td
                  { background: $blueprint-table-stripe-color; }
```

Having the .striped class on `table.striped tr:nth-child(even) td` makes sense as the rule is pretty generic, however its inconsistent to not put it on the second selector `table tr.even            td`.

After looking at the _typography.css that comes with blueprint I see no reason why .striped shouldn't be put on the second selector. The following is the definitions in blueprint.

``` css
tbody tr:nth-child(even) td,
tbody tr.even td  {
  background: #e5ecf9;
}
```

Thus I propose that .striped be placed on the second rule.
