### ISSUE TITLE
input-placeholder mixin broken on master

### ISSUE THREAD

**Issue by Anahkiasen** [Compass/compass#1182]
The old `input-placeholder` code was the following :

``` scss
@mixin input-placeholder {
  @if $experimental-support-for-webkit {
    &::-webkit-input-placeholder {
      @content;
    }
  }
  // etc
}
```

This worked well, however since the code was changed to allow custom selectors :

``` scss
@mixin input-placeholder($selector: "") {
  @if $experimental-support-for-webkit {
    #{$selector}::-webkit-input-placeholder { @content; }
  }
 // etc
}
```

A space gets added before the semi-colons, resulting in the rule being ignored :

``` css
input ::-webkit-input-placeholder, textarea ::-webkit-input-placeholder {
  color: #bd4128; }
```
