### ISSUE TITLE
background-image + linear-gradient screws url() containing variables

### ISSUE THREAD

**Issue by arminrosu** [Compass/compass#1185]
Hey all,

I am in the process of converting a big project from pure SASS to compass. I've come across the following issue.

All image urls are written like follows:

```
$images: '/example/path/images';
background: url(#{$images}/example.gif);
```

In SASS, this compiles nicely to:

```
background: url(/example/path/images/example.gif);
```

However, after importing (and using) `compass/css3/images`, it compiles to this:

```
background: url(linear-gradient(top, #0000ff, #ff0000)/example.gif);
```

**Source**

``` sass
// Compass Configuration
@import "compass/support";
$legacy-support-for-ie8: true;

// Compass Mixins
@import "compass/css3/images";

// Variables
$images: '/example/path/images';

.compass-linear-gradient {
    @include background-image( linear-gradient(top, blue, red) );
}

.interpolated-bg {
    background: url(#{$images}/example.gif);
}

.string-concatenated-bg {
    background: url($images + '/example.gif');
}
```

**Compiled CSS (with Codekit & Scout)**

Notice `linear-gradient(top, #0000ff, #ff0000)` used to replace `$images`, not `/example/path/images`.

``` css
/* line 11, ../sass/styles.scss */
.compass-linear-gradient {
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #0000ff), color-stop(100%, #ff0000));
  background-image: -webkit-linear-gradient(top, #0000ff, #ff0000);
  background-image: -moz-linear-gradient(top, #0000ff, #ff0000);
  background-image: -o-linear-gradient(top, #0000ff, #ff0000);
  background-image: linear-gradient(top, #0000ff, #ff0000);
}

/* line 15, ../sass/styles.scss */
.interpolated-bg {
  background: url(linear-gradient(top, #0000ff, #ff0000)/example.gif);
}

/* line 19, ../sass/styles.scss */
.string-concatenated-bg {
  background: url("linear-gradient(top, #0000ff, #ff0000)/example.gif");
}
```

**Expected Result**

``` css
/* line 11, ../sass/styles.scss */
.compass-linear-gradient {
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #0000ff), color-stop(100%, #ff0000));
  background-image: -webkit-linear-gradient(top, #0000ff, #ff0000);
  background-image: -moz-linear-gradient(top, #0000ff, #ff0000);
  background-image: -o-linear-gradient(top, #0000ff, #ff0000);
  background-image: linear-gradient(top, #0000ff, #ff0000);
}

/* line 15, ../sass/styles.scss */
.interpolated-bg {
  background: url(/example/path/images/test.gif);
}

/* line 19, ../sass/styles.scss */
.string-concatenated-bg {
  background: url("/example/path/images/test.gif");
}
```

**Solution**

The culprit is `background-image()`. Using `background()` doesn't produce this issue, but the documentation doesn't make it clear we should use only this one for linear gradients, or that `background-image()` doesn't support them.

Thanks and HTH
