### ISSUE TITLE
sprite-base-class producing unexpected results

### ISSUE THREAD

**Issue by darren131** [Compass/compass#1245]
Hi,

Apologies if this has been raised already. I'm wanting to change the prefix of my sprites. Eg:

``` css
@import "compass";

$icon-sprite-base-class: ".sprite-";
@import "icon/*.png";

@include all-icon-sprites;
```

I assumed this would do the trick but the CSS it produces it not correct... (or is it something I'm doing wrong?)

``` css
.sprite-, .icon-apple, .icon-facebook, .icon-twitter, .icon-youtube {
  background: url('/assets/images/icon-s4a46a33258.png') no-repeat;
}
[etc]
```

I would expect to see the following:

``` css
.sprite--apple, .sprite--facebook, .sprite--twitter, .sprite--youtube {
  background: url('/assets/images/icon-s4a46a33258.png') no-repeat;
}
[etc]
```

Any ideas would be awesome! 

Thanks,
Darren
