### ISSUE TITLE
Repeated sprite generation when using the same sprite across different files

### ISSUE THREAD

**Issue by verlok** [Compass/compass#1251]
Hi,
I'm using Compass to generate CSS sprites. 

The only way I could find to define a sprite once and use it across different .scss files is the following:
- create a `_variables.scss` partial file
- define the sprite inside the `_variables.scss` partial file
- import the `_variables.scss` partial in every .scss file

**Example**

_variables.scss file:

```
$siteSprite-spacing: 20px; 
@import "siteSprite/*.png";
```

firstPage.scss file:

```
@import "../variables.scss";

.close {
    @include siteSprite-sprite(close, true);
}
```

secondPage.scss file:

```
@import "../variables.scss";

.viewMore {
    @include siteSprite-sprite(arrow, true);
}
```

**And this works, but...**

The problem is that every time that Compass compiles the scss files (firstPage.scss, secondPage.scss) it reads the _variables.scss partial and then reads all the images, trying to generate the sprite each time.

The result is that the _compile_ process ends up in this:

```
   create generated_images/siteSprite-s526a535d08.png
unchanged generated_images/siteSprite-s526a535d08.png
   create css/firstPage.css 
unchanged generated_images/siteSprite-s526a535d08.png
   create css/secondPage.css
unchanged generated_images/siteSprite-s526a535d08.png
   create css/thirdPage.css
unchanged generated_images/siteSprite-s526a535d08.png
```

And this is extremely slow, because I have many pages and many files inside the siteSprite image folder.

**The issue is...**

Don't you think that compass should "remember" that it already executed the @import "siteSprite/*.png" and avoid trying to generate the sprite again?

**Comment by verlok** [comment]
NOTE: The behaviour I'm suggesting "avoid trying to generate the sprite again" should function only within the "compile" command, whereas within the "watch" command the current behaviour is correct.

**Comment by scottdavis** [comment]
It should already be doing what you suggest. Can I get some more info? What OS, ruby version, and compass version

**Comment by verlok** [comment]
It's on Windows, Ruby 1.9.3, Compass 0.12.2

I think the problem is that we are running the compass compile command on a
build machine so we're obligated to use the --force parameter to avoid
compass use its own cache.

In this case we'd need a lighter --force parameter that forces only the
compile of the CSS files and doesn't forces the sprites.

2013/4/14 Scott Davis notifications@github.com

> It should already be doing what you suggest. Can I get some more info?
> What OS, ruby version, and compass version

**Comment by scottdavis** [comment]
oh, this windows issue has been fixed in the current alpha build. if you run `gem install compass --pre` this "should" be fixed but, a lot of things have changed so you may want to look at the change log first: https://github.com/chriseppstein/compass/blob/d1689f8a6519f2ffd8e991f45055576056153d1a/doc-src/content/CHANGELOG.markdown

**Comment by verlok** [comment]
Thank you, as I'm not in a rush to optimize compile performance optimization I think I'll wait the alpha to become stable. 

Thank you again for your quick replies. 

## 

Andrea Verlicchi
www.andreaverlicchi.eu
Twitter: @verlok

**Comment by chriseppstein** [comment]
Note: with the import-once plugin, this behavior should go away: https://github.com/chriseppstein/compass/blob/master/import-once/README.md

**Comment by verlok** [comment]
In fact, using import-once, the behavior doesn't go away.

I installed import-once using the gem command (gem install compass-import-once), cleaned the output css files, and then compiled again, but I get:

   create generated_images/siteSprite-s526a535d08.png
unchanged generated_images/siteSprite-s526a535d08.png
   create css/firstPage.css 
unchanged generated_images/siteSprite-s526a535d08.png
   create css/secondPage.css
unchanged generated_images/siteSprite-s526a535d08.png
   create css/thirdPage.css
unchanged generated_images/siteSprite-s526a535d08.png

Should I enable import-once somehow?
Any hints?

**Comment by JawsomeJason** [comment]
Bump.  I would love to know how to get compass-import-once to work with this as well.

**Comment by jednano** [comment]
I've noticed that running the `sprite-url` helper multiple times is what re-checks the sprite is unchanged or not. I got around this by caching the `sprite-url` in a variable for my use case, but I hope this helps target the problem for others.

**Comment by verlok** [comment]
@jedmao could you please provide the code you used to cache the sprite-url?

**Comment by jednano** [comment]
@verlok 

``` scss
$bem-blocks: (
    "foo",
    "bar",
    "baz"
);

$sprite-files: ();

/*
 * Generate BEM-style silent classes for BEM sprites
 *
 * sprites/foo/
 *   bar-baz.png
 *   qux.png
 *
 * Generates: %foo-sprites__bar-baz and %foo-sprites__qux
 * Provides: width, height and background: <url> <position> no-repeat.
 */
@each $block in $bem-blocks {

    @if str-index($block, "_") {
        @error "BEM sprite blocks must be dasherized.";
    }

    %#{$block}-sprites {

        $map: sprite-map("sprites/#{$block}/*.png", $spacing: 10px);

        // cache sprite-url, because it slows down compass compile
        $url: sprite-url($map);

        @each $name in sprite-names($map) {

            @if str-index($name, "_") {
                @error "BEM sprite files must be dasherized.";
            }

            $sprite-files: map-merge($sprite-files, (
                #{$block}-sprite__#{$name}: sprite-file($map, #{$name})
            ));

            &__#{$name} {
                background: $url sprite-position($map, $name) no-repeat;
                @include sprite-dimensions($map, $name);
            }
        }
    }
}
```

**Comment by verlok** [comment]
@jedmao I fail to understand what that code generates... does it create one class for every image?

To anybody: we're not using the "one image == one class" approach because we have some parts of HTML that we can't edit. So we use sprites like the following.

**file _variables.scss**

``` SCSS
// SPRITE VARIABLES

$spritesSpacing: 10px;
$siteSpritesMap: sprite-map("desktop/siteSprites/*.png", $spacing: $spritesSpacing);
$siteSprites2xMap: sprite-map("desktop/siteSprites2x/*.png", $spacing: $spritesSpacing * 2);

// SPRITES MIXINS

@mixin use1xSprite($sprite, $spriteMap, $renderSize, $offsetX: 0, $offsetY: 0) {
    background: transparent sprite-url($spriteMap) no-repeat sprite-position($spriteMap, $sprite, $offsetX, $offsetY);
    @if ($renderSize) {
        height: image-height(sprite-file($spriteMap, $sprite));
        width: image-width(sprite-file($spriteMap, $sprite));
    }
}

@mixin use2xSprite($sprite, $sprite2xMap, $renderSize, $offsetX: 0, $offsetY: 0) {
    $spritePosition: sprite-position($sprite2xMap, $sprite, $offsetX * 2, $offsetY * 2);
    background: transparent sprite-url($sprite2xMap) no-repeat nth($spritePosition, 1) / 2 nth($spritePosition, 2) / 2;
    background-size: (image-width(sprite-path($sprite2xMap)) / 2) (image-height(sprite-path($sprite2xMap)) / 2);
    @if ($renderSize) {
        height: image-height(sprite-file($sprite2xMap, $sprite)) / 2;
        width: image-width(sprite-file($sprite2xMap, $sprite)) / 2;
    }
}

@mixin use1x2xSprite($sprite, $spriteMap, $sprite2xMap, $renderSize: false, $offsetX: 0, $offsetY: 0) {
    @include use1xSprite($sprite, $spriteMap, $renderSize, $offsetX, $offsetY);
    @media (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) {
        @include use2xSprite($sprite, $sprite2xMap, $renderSize, $offsetX, $offsetY);
    }
}
```

**files: site.scss, firstPage.scss, secondPage.scss, etc.**

``` SCSS
// VARIABLES INCLUSION

@import "variables"

// SPRITE USAGE

.someSelectorInAnyPage {
    @include use1x2xSprite(sprite, $siteSpritesMap, $siteSprites2xMap, true);
}
```

The result is that the compile process ends up in this:

```
   create generated_images/siteSprite-s526a535d08.png
   create generated_images/siteSprite2x-s526a535d08.png
unchanged generated_images/siteSprite-s526a535d08.png
unchanged generated_images/siteSprite2x-s526a535d08.png
   create css/firstPage.css 
unchanged generated_images/siteSprite-s526a535d08.png
unchanged generated_images/siteSprite2x-s526a535d08.png
   create css/secondPage.css
unchanged generated_images/siteSprite-s526a535d08.png
unchanged generated_images/siteSprite2x-s526a535d08.png
   create css/thirdPage.css
unchanged generated_images/siteSprite-s526a535d08.png
unchanged generated_images/siteSprite2x-s526a535d08.png
```

This is extremely slow, because I have many pages and many files inside the siteSprite image folder.

What are we doing wrong? Is the multiple _variables import that makes compass try to create a sprite map so many times (more probable)? Or is the call to the `@use1xSprite` or `@use2xSprite` mixins (less probable)?

@chriseppstein, does the compass-import-once gem solve this case, or is it meant to solve other problems?

**Comment by jednano** [comment]
@verlok my code generates one **_silent_** class for every sprite. For example, if you had a `sprites/app` folder with images `foo.png` and `bar.png` inside of it, it would generate:

``` scss
%app-sprites__foo {
  background: url(images/app-sprite.png) 0 0 no-repeat;
  width: 30px;
  height: 30px;
}

%app-sprites__bar {
  background: url(images/app-sprite.png) 0 -30px no-repeat;
  width: 20px;
  height: 15px;
}
```

Now, you can implement it as many times as you like, as follows:

``` scss
.someSelectorInAnyPage {
  @extend %app-sprites__foo;
}

.anotherSelector {
  @extend %app-sprites__foo;
  border: 1px solid gold;
}

.yetAnotherSelector {
  @extend %app-sprites__bar;
  margin: 10px;
}
```

which would generate the following CSS:

``` css
.someSelectorInAnyPage, .anotherSelector {
  background: url(images/app-sprite.png) 0 0 no-repeat;
  width: 30px;
  height: 30px;
}

.anotherSelector {
  border: 1px solid gold;
}

.yetAnotherSelector {
  background: url(images/app-sprite.png) 0 -30px no-repeat;
  width: 20px;
  height: 15px;
}

.yetAnotherSelector {
  margin: 10px;
}
```

You don't have to edit your HTML. I strongly suggest you read the [Sass documentation on @extend](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#extend) and use it religiously. Also read [Extending silent classes in Sass](http://csswizardry.com/2014/01/extending-silent-classes-in-sass/) and [Understanding placeholder selectors](http://thesassway.com/intermediate/understanding-placeholder-selectors). Silent classes and placeholder selectors are the same thing.

**Comment by verlok** [comment]
Great tip!
Thank you very much for the hint!

**Comment by jednano** [comment]
Maybe we can close the issue now?

**Comment by verlok** [comment]
Yes!

**Comment by verlok** [comment]
I mean: no, because it doesn't solve my original question :)

**Comment by jednano** [comment]
I agree that `@import`ing a sprite multiple times should attempt to re-build a sprite file. Would be nice if Compass was smart enough to prevent that from happening.

**Comment by szczups** [comment]
Hi @verlok. I was having similar issue, when using mixin for my sprites. Apparently after removing sprite-url($sprites) from mixin and substitutting it with variable (like this: $sprites-url: sprite-url($sprites) ) the problem went away. I'm not sure if this is helpful. I always thought it's supposed to happen, but I'm really glad that it's not happening any more. 

For more information - I'm on Windows 8.1, with Ruby 2.0, using Grunt as a task runner. I'm not using force flag (when I tried using it, I got an endless loop). I'm using default sprite generation engine and my compass version is 1.0.0 alpha 19 .

**Comment by T2L** [comment]
Hi @szczups, 

Seems like I'm having the same issue. Could you provide more details on how to fix it?

Thanks.

**Comment by szczups** [comment]
@T2L , sure thing. I'll try to explin simply by pasting example from mixin above: 

``` scss

@mixin use1xSprite($sprite, $spriteMap, $renderSize, $offsetX: 0, $offsetY: 0) {
    background: transparent sprite-url($spriteMap) no-repeat sprite-position($spriteMap, $sprite, $offsetX, $offsetY);
    @if ($renderSize) {
        height: image-height(sprite-file($spriteMap, $sprite));
        width: image-width(sprite-file($spriteMap, $sprite));
    }
}
```

In my case, the problem was with the **$sprite-url($spriteMap)**. What I did? Instead of calling directly $sprite-url() I put there variable , wchich by default I keep in _vars.scss. So code after change would look like this: 

``` scss
$sprite-url : sprite-url($spriteMap); //here of course $spriteMap. In my case $spriteMap was simply $sprites which defined by default in compass, so I didn't have to pass it to mixin. 

@mixin use1xSprite($sprite, $spriteMap, $renderSize, $offsetX: 0, $offsetY: 0) {
    background: transparent $sprite-url no-repeat sprite-position($spriteMap, $sprite, $offsetX, $offsetY);
    @if ($renderSize) {
        height: image-height(sprite-file($spriteMap, $sprite));
        width: image-width(sprite-file($spriteMap, $sprite));
    }
}
```

I hope it's understandable. And after I did that, I only get one message - that spritemap was unchanged, without checking each sprite element.

**Comment by T2L** [comment]
Hi @szczups,

Thanks! Your approach does fix the issue!

**Comment by JawsomeJason** [comment]
@verlock now that this creates a file size bloat issue, should this necessarily be closed?  Do we want to accept one fix with another problem?

**Comment by verlok** [comment]
So to wrap this up, 
this is the solution of this issue:

``` scss
@import "compass/utilities/sprites";

// --- VARIABLES ---

// Generic spacing (at 1x) for sprites
$spacing-sprites-generic: 10px;

// SiteSprites maps
$flagSprites1xMap: sprite-map("flagSprites1x/*.png", $spacing: $spacing-sprites-generic);
$flagSprites2xMap: sprite-map("flagSprites2x/*.png", $spacing: $spacing-sprites-generic * 2);

// SiteSprites urls
$flagSprites1xUrl: sprite-url($flagSprites1xMap);
$flagSprites2xUrl: sprite-url($flagSprites2xMap);

// --- MIXINS ---

// Any density sprite
@mixin useNxSprite($sprite, $spriteMap, $spriteNxUrl, /* OPTIONAL PARAMETERS -> */ $multiplier: 1, $renderSize: false, $offsetX: 0, $offsetY: 0) {
    $spritePosition: sprite-position($spriteMap, $sprite, $offsetX * $multiplier, $offsetY * $multiplier);
    background: transparent $spriteNxUrl no-repeat nth($spritePosition, 1) / $multiplier nth($spritePosition, 2) / $multiplier;
    @if ($multiplier > 1) {
        background-size: (image-width(sprite-path($spriteMap)) / $multiplier) (image-height(sprite-path($spriteMap)) / $multiplier);
    }
    @if ($renderSize) {
        height: image-height(sprite-file($spriteMap, $sprite)) / $multiplier;
        width: image-width(sprite-file($spriteMap, $sprite)) / $multiplier;
    }
}

// Single and double density sprite
@mixin use1x2xSprite($sprite, $spriteMap, $sprite2xMap, $sprite1xUrl, $sprite2xUrl, /* OPTIONAL PARAMETERS -> */ $renderSize: false, $offsetX: 0, $offsetY: 0) {
    @include useNxSprite($sprite, $spriteMap, $sprite1xUrl, 1, $renderSize, $offsetX, $offsetY);
    @media (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) {
        @include useNxSprite($sprite, $sprite2xMap, $sprite2xUrl, 2, $renderSize, $offsetX, $offsetY);
    }
}

// --- Utility mixin to avoid passing parameters at every usage ---

@mixin flagSprites($spriteName, $renderSize: false, $offsetX: 0, $offsetY: 0) {
    @include use1x2xSprite($spriteName, $flagSprites1xMap, $flagSprites2xMap, $flagSprites1xUrl, $flagSprites2xUrl, $renderSize, $offsetX, $offsetY);
}

// ----- USAGES ----

.flag-1 {
    @include flagSprites(fr, true, 5, 5);
}

.flag-2 {
    @include flagSprites(de);
}

.flag-3 {
    @include flagSprites(be);
}

.flag-4 {
    @include flagSprites(jp);
}

.flag-5 {
    @include flagSprites(it);
}
```

**Comment by verlok** [comment]
@thejase I deleted my comment because...

1) the problem of the "bloat" dowsn't depend on the initial issue opened here (we've gone off topic)
2) to stay off topic, for what I experienced there isn't any other solution except the bloat if we want to use different sprites for different screen densities, as SASS doesn't accept the `extend` inside a `@media` directive, throws an error, and kills your build.

In other words, the ideal solution would be to do the following:

``` scss
@import "compass/utilities/sprites";

@import "flagSprites1x/*.png";
@import "flagSprites2x/*.png";

@mixin flagSprite($spriteName) {
    @include flagSprites1x-sprite($spriteName);
    @media (screen) and (min-device-pixel-ratio: 1.5) {
        @include flagSprites2x-sprite($spriteName);
    }
}
```

That, in our dreams, would produce the following css code:

``` css
.flagSprites1x-sprite, .flag-1, .flag-2, .flag-3, .flag-4, .flag-5 {
  background-image: url('/images/flagSprites1x-s4ad21c3bd3.png');
  background-repeat: no-repeat;
}

@media (screen) and (min-device-pixel-ratio: 1.5) {
  .flagSprites2x-sprite, .flag-1, .flag-2, .flag-3, .flag-4, .flag-5  {
    background-image: url('/images/flagSprites2x-s6642ef876f.png');
    background-repeat: no-repeat;
  } 
}
```

But instead of doing that, it just throws the error "You may not @extend an outer selector from within @media.", but it's a SASS limit and it doesn't have nothing to do with compass.
