### ISSUE TITLE
Compass compiling extremely slowly

### ISSUE THREAD

**Issue by andrewcroce** [Compass/compass#1265]
Recently (and quite suddenly) I have noticed Compass is taking an absurd amount of time to compile my project, upwards of 2 minutes. I use the `compass watch` command to track changes on my project, which is on a mounted Transmit disk, though it seems equally slow when manually doing `compass compile`.

I am running the lates version Compass 0.12.2 and Sass 3.2.7, in a Foundation 4 project.

Any help would be very much appreciated, I am stuck here and waiting 2 minutes every time I save a file is not very sustainable. Thanks!

**Comment by Somebi** [comment]
Yeah same here. Something strange is happening inside there. Some junk loops probably.

**Comment by scottdavis** [comment]
can you make an example repo that is compiling slow for debugging purposes?

**Comment by Somebi** [comment]
It's loading CPU for about 1-2 mins from start and then the load disappear.

**Comment by andrewcroce** [comment]
FYI, it was a particular @extend statement that was causing the delay,
which had several nested @extends. Looks like you have to be careful
extending things that are already extending other things.

On Wed, May 1, 2013 at 10:41 AM, Deniss Abramovs
notifications@github.comwrote:

> It's loading CPU for about 1-2 mins from start and then the load disappear.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chriseppstein/compass/issues/1265#issuecomment-17284590
> .

## 

Andrew Croce
andrew.croce@gmail.com
andrewcroce.com
732.995.0590

**Comment by alanhogan** [comment]
Observing 100% CPU usage from `compass compile` and/or `compass watch`, myself, as well.

Compass 1.0.0.alpha.21

**Comment by aubricus** [comment]
+1

Upgraded to `Compass 1.0.1 (Polaris)` today; noticed compile times are very slow (compared to the previous version of Compass running on the same project). Activity monitor shows 100% CPU usage from the `compass watch` process when compiles are triggered by file changes.

My project currently runs through a few loops to output some presentational classes useful for prototyping. Compile time is at least 10-20 seconds. I was running Compass 0.12.x just yesterday and compile times were not this slow.

I am running compass, bourbon, susy, and breakpoint. 

Removing bourbon has no effect. I can't really remove susy or breakpoint as the code depends heavily on these two libraries.

Here's the only file in my project that actually compiles css (at the moment):

``` scss
@mixin loop-columns($class, $total-columns: $built-twbs-columns) {
    @for $i from (0 + 1) through $total-columns {
        .col-#{$class}-#{$i} {
            @include span($i);
        }
    }
}

@mixin loop-columns-offset($class, $total-columns: $built-twbs-columns) {
    @for $i from (-1 + 1) through ($total-columns - 1) {
        .col-#{$class}-offset-#{$i} {
            @include pre($i of $total-columns);
        }
    }
}

@mixin loop-columns-pull($class, $total-columns: $built-twbs-columns) {
    @for $i from (0 + 1) through $total-columns {
        .col-#{$class}-pull-#{$i} {
            right: span($i of $total-columns);
        }
    }
}

@mixin loop-columns-push($class, $total-columns: $built-twbs-columns) {
    @for $i from (0 + 1) through $total-columns {
        .col-#{$class}-pull-#{$i} {
            left: span($i of $total-columns);
        }
    }
}

[class*=col-] {
    // stub
}

.row {
    @include span(full no-gutters break);
}

@include loop-columns(xs);
@include loop-columns-offset(xs);
@include loop-columns-pull(xs);
@include loop-columns-push(xs);

@include breakpoint($twbs-breakpoint-sm) {
    @include loop-columns(sm);
    @include loop-columns-offset(sm);
    @include loop-columns-pull(sm);
    @include loop-columns-push(sm);
}

@include breakpoint($twbs-breakpoint-md) {
    @include loop-columns(md);
    @include loop-columns-offset(md);
    @include loop-columns-pull(md);
    @include loop-columns-push(md);
}

@include breakpoint($twbs-breakpoint-lg) {
    @include loop-columns(lg);
    @include loop-columns-offset(lg);
    @include loop-columns-pull(lg);
    @include loop-columns-push(lg);
}
```
