### ISSUE TITLE
Syntax Error when passing calc to linear gradients.

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#1277]
See: https://twitter.com/DavidPdrsn/status/331325571365744640

Until fixed here's a work-around:

``` scss
.calc-bg {
    background: unquote("linear-gradient(to right, white calc(100% - 50px), transparent calc(100% - 50px))");
}
```
