### ISSUE TITLE
Support for multiple image and font directories

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#1286]
Currently, if you have images from multiple locations you have to copy them to some known location under the images directory in order to reference them with `image-url`. Similarly for fonts. I'm toying with the idea of adding multiple search paths for images and fonts. The syntax for the config.rb file would be:

``` ruby
add_image_location "path/to/images/locally", "path/to/http/location"
add_font_location "path/to/images/locally", "path/to/http/location"
```

This would also enable finding sprite source files in multiple locations. It's not clear whether this would mean that all images matching the glob in all paths would get merged together or whether the first path for which the glob matches would be used. If you have a preference please let me know which and why.

This adds a fair bit of complexity, so my preference is to not add it unless there's a demand for it beyond the few use cases I've heard of. Specifically, if you'd like this, please let me know why it is preferable to copying files into a location that shares a common root directory with another images directory.

**Comment by zeelot** [comment]
This would be great for me because I use a PHP framework that separates functionality into modules which can each contain their own assets (css/img/js). I want my main compass application to be able to pull images from any of my enabled modules without having to write some custom script to copy all of the assets out of the modules.

I currently have an import path for the scss files in every module but cannot do the same for the other needed file types.

**Comment by stephenway** [comment]
In my team's setup we have each site setup as a compass project with it's own image directory but we also have a parent directory for common assets.

``` css
add_image_location "images", "/_assets/images"

.foo {
  background-image: image-url('image.png');
}
```

This would provide more portability and caching for our ad-hoc compass extension instead of doing something like 

``` css
$default-asset-path: "/_assets";

.foo {
  background-image: url('#{$default-asset-path}/images/image.png');
}
```
