### ISSUE TITLE
allow one scss file to be split into different css files

### ISSUE THREAD

**Issue by fuddl** [Compass/compass#1300]
I would like to exclude certain statements into different files.

could be usefull in situations like this:

```
.foo {
  font-weight:bold;
  @put-into(ie6.css) {
    font-weight:normal;
  }
}
```

or like this:

```
.foo {
  @put-into(red-theme.css) {
    background-color: red;
  }
  @put-into(blue-theme.css) {
    background-color: blue;
  }
}
```

**Comment by hagenburger** [comment]
That would be a Sass, not a Compass issue. 

I’m solving this like:

``` scss
// red-theme.scss
$theme = red;
@import "mixins.scss";
@import "styles.scss";
```

``` scss
// blue-theme.scss
$theme = blue;
@import "mixins.scss";
@import "styles.scss";
```

``` scss
// _mixins.scss
@mixin for-red-theme {
  @if $theme == red {
    @content;
  }
}

@mixin for-blue-theme {
  @if $theme == blue {
    @content;
  }
}
```

``` scss
// _styles.scss
.foo {
  @include for-red-theme {
    background-color: red;
  }
  @include for-blue-theme {
    background-color: blue;
  }
}
```
