### ISSUE TITLE
linear-gradient mixin conflicts with CSS background property

### ISSUE THREAD

**Issue by pathes** [Compass/compass#1358]
When I write in SCSS `background: linear-gradient(...)` I expect it to be CSS3 property. Instead it's parsed as SCSS mixin and I get `background: _linear-gradient(...)` in stylesheet.

There's a workaround for it, `background: #{"linear-gradient(...)"}`, but I believe it should be able to use linear-gradient without such hacks.

**Comment by cimmanon** [comment]
The linear-gradient function is intended to be used in combination with the background family of mixins:

http://compass-style.org/reference/compass/css3/images/

``` scss
.foo {
    @include background(linear-gradient(black, white));
}
```

**Comment by mgol** [comment]
That's true, it's just the name is very unfortunate. Compass shouldn't mess with a pure CSS declaration. As it is now, the following is valid CSS:

``` css
#id {
    background-image: linear-gradient(to bottom, hsl(0, 80%, 70%), #bada55);
}
```

but it becomes invalid when passed through Compass. Compass functions names shouldn't conflict with CSS functions names.

**Comment by mirisuzanne** [comment]
The sample you posted works fine for me, both on stable and alpha installations of Compass. I can't re-create your problem at all. Can you post a full sample - input and output - along with the versions you have installed?

With Compass 0.13.alpha.4, I can do this:

``` scss
// input
.include {
  @include background-image(linear-gradient(to bottom, hsl(0, 80%, 70%), #bada55));
}

.solo {
  background-image: linear-gradient(to bottom, hsl(0, 80%, 70%), #bada55);
}

// output
.include {
  background-image: -webkit-linear-gradient(top, #f07575, #bada55);
  background-image: -moz-linear-gradient(top, #f07575, #bada55);
  background-image: -o-linear-gradient(top, #f07575, #bada55);
  background-image: linear-gradient(to bottom, #f07575, #bada55);
}

.solo {
  background-image: linear-gradient(to bottom, #f07575, #bada55);
}
```

Compass 0.12.2 doesn't support the new "to" syntax inside the include - but it still works solo:

``` scss
// input
.solo {
  background-image: linear-gradient(to bottom, hsl(0, 80%, 70%), #bada55);
}

// output
.solo {
  background-image: linear-gradient(to bottom, #f07575, #bada55);
}
```
