### ISSUE TITLE
Properties and values are incorrectly prefixed together

### ISSUE THREAD

**Issue by mgol** [Compass/compass#1360]
The following:

``` scss
#id {
    @include transition(transform 1s);
}
```

is evaluated by Compass (from master) to:

``` css
#id {
    -webkit-transition: -webkit-transform 1s;
    -moz-transition: -moz-transform 1s;
    transition: transform 1s;
}
```

The problem is, Chrome has unprefixed `transition` but not `transform` which makes this mixin work incorrectly there.
