### ISSUE TITLE
contrast-color() function now only works with colors? (v13 alpha 8)

### ISSUE THREAD

**Issue by cimmanon** [Compass/compass#1418]
Previously, the contrast-color function could be used with any values for the `$light` and `$dark` arguments, but now they _must_ be colors.  I was using this function to determine the offset for a text-shadow to give it an embossed look, depending on the color of text:

``` scss
$color: red;
.foo {
    color: $color;
    $shadow-color: contrast-color($color, rgba(black, .8), rgba(white, .3));
    $shadow-offset: contrast-color($color, 1px, -1px);
    @include text-shadow(0 $shadow-offset 0 $shadow-color);
}
```

The error from Compass:

```
Line 10 of _brightness.scss: $color: 1px is not a color for `red'
```

Am I the only person who was using this function for something other than color?  Does having a new function that behaves like the original make sense?
