### ISSUE TITLE
transition-property mixin prefixing problem

### ISSUE THREAD

**Issue by jrencz** [Compass/compass#1423]
``` scss
E {
    @include transition-property(transform, height);
}
```

Results in

``` css
E {
    transition-property(transform, height);
}
```

Instead of 

``` css
E {
    transition-property(-webkit-transform, height);
    transition-property(transform, height);
}
```

default $transitionable-prefixed-values of 'transform, transform-origin" is not applied

**Comment by mgol** [comment]
I can confirm that this is still a problem with newest Compass alpha; if one has set, for example, to support only the latest Chrome which has unprefixed `transition`, but not `transform`, the latter doesn't get prefixed. This concerns the shorthand as well; the following:

``` scss
div {
    @include transition(transform 0.3s);
}
```

gets transfered to this:

``` css
div {
    transition: transform 0.3s;
}
```

instead of expected:

``` css
div {
    transition: -webkit-transform 0.3s;
    transition: transform 0.3s;
}
```
