### ISSUE TITLE
Compass 0.13.alpha.10 doesn't generate IE10 flexbox mixins

### ISSUE THREAD

**Issue by mgol** [Compass/compass#1427]
Given the following `config.rb`:

``` ruby
css_dir = "."
sass_dir = "."
output_style = :expanded
relative_assets = true
line_comments = false
```

and a file `styles.scss`:

``` scss
$supported-browsers: ("chrome", "firefox", "ie", "safari");
$browser-minimum-versions: (
    chrome: "30",
    firefox: "24",
    ie: "10",
    safari: "7",
);

@import "compass/css3";

div {
    @include display-flex;
}
```

I am getting the following `styles.css` on `compass compile`:

``` css
div {
  display: -webkit-flex;
  display: flex;
}
```

instead of expected:

``` css
div {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
}
```
