### ISSUE TITLE
Implement headers() in Sass instead of Ruby

### ISSUE THREAD

**Issue by kasperisager** [Compass/compass#1461]
Hi there!

Simply thought I'd share a Sass-implementation of the `headers()` function which is currently implemented in Ruby:

``` scss
@function headers($from, $to: false) {
    @if ($from and not $to) {
        @if (unquote($from) == all) {
            $from: 1;
            $to: 6;
        } @else {
            $to: $from;
            $from: 1;
        }
    } @else {
        $from: if($from, $from, 1);
        $to: if($to, $to, 6);
    }

    $from: min($from, 6);
    $to: min($to, 6);

    $headers: ();

    @for $i from $from through $to {
        $headers: append($headers, #{h}#{$i}, comma);
    }

    @return $headers;
}
```

Is there a reason as to why this function is currently implemented in Ruby?

P.S.: Dead simple alias

``` scss
@function headings($from, $to: false) {
    @return headers($from, $to);
}
```
