### ISSUE TITLE
Background-position not using percentages.

### ISSUE THREAD

**Issue by nearestnabors** [Compass/compass#1473]
I know I've used `$xxxx-use-percentages: true;` to get background images to use percents in the past. Not sure why it doesn't seem to be working this time around... 

Gemfile:

``` ruby
GEM
  remote: https://rubygems.org/
  specs:
    breakpoint (2.0.7)
      compass (>= 0.12.1)
      sass (>= 3.2.0)
    chunky_png (1.2.9)
    compass (0.12.2)
      chunky_png (~> 1.2)
      fssm (>= 0.2.7)
      sass (~> 3.1)
    fssm (0.2.10)
    rb-fsevent (0.9.3)
    sass (3.2.12)

PLATFORMS
  ruby

DEPENDENCIES
  breakpoint
  compass
  rb-fsevent
  sass
```

Scss:

``` scss
/* Items */
@import "compass/utilities/sprites";
@import "items/*.png";
$items-use-percentages: true;

// socks
.socks {
  @include set-dimensions(50px, 60px, $parent-width);
  @include set-position(975px, 141px, $parent-width);
  @extend %items;
  @include items-sprite(socks-dirty);
}
```

CSS:

``` css
  /* Items */
  /* line 66, items/*.png */
  .items-sprite, .socks, .socks-place, .socks-place.droppable, .socks-place.clean {
    background: url('/img/items-s0a4c5e4520.png') no-repeat;
  }

  /* line 9, ../sass/_items.scss */
  .socks {
    -webkit-background-size: 100% auto;
    -moz-background-size: 100% auto;
    -o-background-size: 100% auto;
    background-size: 100% auto;
    width: 4.11862%;
    padding-top: 4.94234%;
    left: 80.31301%;
    top: 11.6145%;
    background-position: 0 -224px;
  }
```
