### ISSUE TITLE
The Vertical Rhythm module sticks only to the last established baseline

### ISSUE THREAD

**Issue by rpkoller** [Compass/compass#1487]
I initially hoped things would work out of the box, since it was possible to establish different baselines for different viewports, but then it seems the adjust-font-size-to mixin and related stick to the last set baseline in their calculation: 

http://sassmeister.com/gist/7992795
- e.g.  $mod0 is 20px and $mood0 26px 
- then the font-size of p is in the wrong context. i would have expected 1em referring to the 20px base size but 0.76923em refers to 26px instead. the values within the breakpoint are correct besides. 

In case this is expected behaviour i would suggest that the adjust-font-size-to mixin and the other related mixins orient themselves to the baseline set to the present breakpoint or fall back to the matching "base" baseline. Would be neat. Best regards r.

**Comment by mirisuzanne** [comment]
Breakpoints don't exist as a scope in Sass or Compass, and I don't think they really _could_ - since it is easy to write media-queries that may or may not overlap in various ways, depending on the client/device/browser. 

``` scss
@include breakpoint(min-width 750px) { $base-size: 10px; }
@include breakpoint((max-height 200px) (orientation landscape)) { $base-size: 20px; }

@include breakpoint(orientation landscape) { /* What context am I in? What's the value of $base-size? */ }
```

Also, "Breakpoint" is a 3rd-party plugin, so not directly integrated with all Compass features.
