### ISSUE TITLE
font-url and ? for iefix

### ISSUE THREAD

**Issue by intellix** [Compass/compass#1491]
Hey, it seems since updating to the latest --pre version of compass, font-url with ? has stopped working. I believe it was working in "Compass 1.0.0.alpha.13" but not anymore in "Compass 1.0.0.alpha.17".

I was using the following:

``` css
@font-face {
    font-family: 'TeXGyreAdventorRegular';
    src: font-url('tex-gyre/texgyreadventor-regular-webfont.eot');
    src: font-url('tex-gyre/texgyreadventor-regular-webfont.eot?#iefix') format('embedded-opentype'),
         font-url('tex-gyre/texgyreadventor-regular-webfont.woff') format('woff'),
         font-url('tex-gyre/texgyreadventor-regular-webfont.ttf') format('truetype'),
         font-url('tex-gyre/texgyreadventor-regular-webfont.svg#TeXGyreAdventorRegular') format('svg');
    font-weight: normal !important;
    font-style: normal !important;
}
```

Which gives a WARNING like so:

``` bash
WARNING: 'texgyreadventor-regular-webfont.eot?' was not found (or cannot be read) in /var/www/my-site/public/fonts/tex-gyre
```

Inside my config.rb, related to fonts I have: 

``` ruby
fonts_dir = "public/fonts"
http_fonts_path = "../../fonts"
```

When I look at the generated CSS, I have the correct CSS, so it's just a warning.

``` css
@font-face {
  font-family: 'TeXGyreAdventorRegular';
  src: url('../../fonts/tex-gyre/texgyreadventor-regular-webfont.eot?1376881808');
  src: url('../../fonts/tex-gyre/texgyreadventor-regular-webfont.eot?#iefix') format("embedded-opentype"), url('../../fonts/tex-gyre/texgyreadventor-regular-webfont.woff?1376881808') format("woff"), url('../../fonts/tex-gyre/texgyreadventor-regular-webfont.ttf?1376881808') format("truetype"), url('../../fonts/tex-gyre/texgyreadventor-regular-webfont.svg?1376881808#TeXGyreAdventorRegular') format("svg");
  font-weight: normal !important;
  font-style: normal !important;
}
```

My ?#iefix is in relation to this: http://stackoverflow.com/a/8636675 as per is generated from fontsquirrel when you download a web-font pack

Thanks, Dom
