### ISSUE TITLE
Issue with the border-radius mixin

### ISSUE THREAD

**Issue by tehauthor** [Compass/compass#1517]
When using @include border-radius(0) the output looks as follows:

 -webkit-border-radius: none;
  -moz-border-radius: none;
  -ms-border-radius: none;
  -o-border-radius: none;
  border-radius: none;

The problem with this is that none isn't a supported value of border radius as per specs and certain browsers (Safari mobile), instead of ignoring it and stripping the border-radius property, as Chrome does, fall back to the previous value of it.

Output should be:

 -webkit-border-radius: 0;
  -moz-border-radius: 0;
  -ms-border-radius: 0;
  -o-border-radius: 0;
  border-radius: 0;

**Comment by mirisuzanne** [comment]
This has already been fixed in the master branch (along with removing unnecessary prefixes):

``` scss
// input
.test { @include border-radius(0); }

// output
.test {
  -moz-border-radius: 0;
  -webkit-border-radius: 0;
  border-radius: 0;
}
```
