### ISSUE TITLE
replace-text-with-dimensions: background-position dimensions are equal to element dimensions

### ISSUE THREAD

**Issue by vanja988** [Compass/compass#1552]
For example this:

``` sass
#main-logo
{
@include replace-text-with-dimensions("main-logo.png", 98px, 86px, false); 
}
```

generates this:

``` css
#main-logo
{
text-indent: -119988px;
overflow: hidden;
text-align: left;
background-image: url('../img/main-logo.png?1391985367');
background-repeat: no-repeat;
background-position: 98px 86px;
width: 98px;
height: 86px;
}
```

...which makes the background image invisible. There should be two additional arguments for background-position values.
