### ISSUE TITLE
Documentation lacks explanation and basic syntax

### ISSUE THREAD

**Issue by Knooq** [Compass/compass#1559]
On Page: http://compass-style.org/reference/compass/helpers/selectors/#nest

I was looking for:  an example of the nest selector function syntax and

NOWHERE is it shown how to invoke these functions, turns out this works; #{nest(".class1", ".class2")}

In general the docs are poor and the syntax is not always along the lines of SASS, you should provide clear examples if you want higher adoption of this framework, particularly given the fact that the compiler balks at a missing semicolon.

Also If you had a contrib/comments section on each page, this would allow for developers to contribute examples, ala api.drupal.org.

But instead I found:
no example

**Comment by cimmanon** [comment]
This has nothing to do with Compass.  Using a function as a selector has never been valid without the use of interpolation.  This is vanilla Sass and it gives the same error:

``` scss
$classes: one, two;
nth($classes, 1) {
    background: blue;
}
```

Even if it were allowed by Sass, you can't use strings (which is what the `nest()` function returns) as selectors without using interpolation anyway (though it is no longer a syntax error):

``` scss
".class1 .class2" {
    background: red;
}
```

Output:

``` css
".class1 .class2" {
  background: red;
}
```
