### ISSUE TITLE
Break-inside mixin (css3/columns) has incorrect output

### ISSUE THREAD

**Issue by cimmanon** [Compass/compass#1561]
In 1.0.0.alpha.18, the break-inside property is emitted twice.

``` scss
.foo {
    /* columns */
    @include columns(30em);
    /* break-inside */
    @include break-inside(avoid);
}
```

Output:

``` css
.foo {
  /* columns */
  -moz-columns: 30em;
  -webkit-columns: 30em;
  columns: 30em;
  /* break-inside */
  break-inside: avoid;
  -webkit-column-break-inside: avoid;
  break-inside: avoid;
}
```

It is also worth noting that the moz prefix is omitted.  However, moz browsers don't support the break-inside property as per the specification.  Instead, they use the page-break-inside property.

http://codepen.io/cimmanon/pen/CcGlE
