### ISSUE TITLE
Sprite class names output with incorrect hierarchy

### ISSUE THREAD

**Issue by Demwunz** [Compass/compass#1564]
I am trying to output the desired class structure:

`.select-flag.select-flag--en`  

however compass is repeating the parent class giving the wrong structure as so:

`.select-flag .select-flag.select-flag--en`

to replicate this, here is my code:

``` scss
.select-flag{
    $select-flag-spacing:15px;
    @import "select-flag/*.png";
    $languages : (en, zh-cn, ja, it, pt, es, de);
    @each $language in $languages {
      &.select-flag--#{$language}{
        @include select-flag-sprite($language);
      }
    }
}
```

from what I can tell, this _should_ give my desired output - but alas, its not. The issue seems to be the & in the @each loop. when i remove it the issue goes, but the output changes to something im not quite looking for. 

compass version 0.12.2
