### ISSUE TITLE
1.0.0.alpha.18: W3C notation linear-gradient warning

### ISSUE THREAD

**Issue by thany** [Compass/compass#1573]
When I try to approach the W3C notation for a linear-gradient, compass spews out a warning. This is the SASS:

```
@include background(linear-gradient(to right, rgba(0,0,0,.15), transparent));
```

The warning is `Cannot determine the opposite position of: to`. I sort-of understand what it's trying to do, so it appears to me that Compass isn't quite up to par with the "new" notation.

Workaround is the old-style notation:

```
@include background(linear-gradient(90deg, rgba(0,0,0,.15), transparent));
```

Can the new notation please be supported as well in Compass? Especially when going `to bottom right`, specifying an agle is really no alternative anymore.

**Comment by cimmanon** [comment]
I cannot confirm (also running 1.0.0.alpha.18).

``` scss
@import "compass/css3/images";
.foo {
    @include background(linear-gradient(to right, rgba(0,0,0,.15), transparent));
}
```

Output:

``` css
.foo {
  background: -moz-linear-gradient(left, rgba(0, 0, 0, 0.15), rgba(0, 0, 0, 0));
  background: -o-linear-gradient(left, rgba(0, 0, 0, 0.15), rgba(0, 0, 0, 0));
  background: -webkit-linear-gradient(left, rgba(0, 0, 0, 0.15), rgba(0, 0, 0, 0));
  background: linear-gradient(to right, rgba(0, 0, 0, 0.15), rgba(0, 0, 0, 0));
}
```
