### ISSUE TITLE
no webkit prefix transition compass 1.0.0.alpha.18

### ISSUE THREAD

**Issue by eradrix** [Compass/compass#1590]
Hi, 
I originally asked this in stackoverflow (http://stackoverflow.com/questions/22247232/no-webkit-prefix-transition-compass-1-0-0-alpha-18) but I was suggested to follow this up here:

I've set "safari": "6" in $browser-minimum-version. It seems that compass outputs -webkit-transform but forgets to output webkit prefixes for all transition mixins.

Did I miss something?

**Comment by chriseppstein** [comment]
please post example code and output with the $debug-browser-support variable set to true.

**Comment by eradrix** [comment]
Here's the result of my investigations:
scss file

``` scss
$browser-minimum-versions: ("chrome": "19", "firefox": "4", "ie": "9", "safari": "6") !global;
$debug-browser-support: true;

@import "compass";

div {
    @include transition-property(transform);
    @include transition-duration(1s);
    @include transition-timing-function(ease-in-out);
    @include translate(0, 0);
    &:hover {
    @include translate(2em, 0);
    }
    content: "#{browser-out-of-scope("safari","5")}";
}
```

Compiled in a draft project using bundler + gems, it turns to

``` css
/* line 6, ../sass/prefixes.scss */
div {
  /* Capability css-transitions is prefixed with -moz because 1.0075% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -moz context. */
  -moz-transition-property: -moz-transform;
  /* Capability css-transitions is not prefixed with -ms because 0% of users are affected which is less than the threshold of 0.1. */
  /* Capability css-transitions is prefixed with -o because 0.14724% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -o context. */
  -o-transition-property: -o-transform;
  /* Capability css-transitions is prefixed with -webkit because 11.42224% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -webkit context. */
  -webkit-transition-property: -webkit-transform;
  transition-property: transform;
  /* Capability css-transitions is prefixed with -moz because 1.0075% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -moz context. */
  -moz-transition-duration: 1s;
  /* Capability css-transitions is not prefixed with -ms because 0% of users are affected which is less than the threshold of 0.1. */
  /* Capability css-transitions is prefixed with -o because 0.14724% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -o context. */
  -o-transition-duration: 1s;
  /* Capability css-transitions is prefixed with -webkit because 11.42224% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -webkit context. */
  -webkit-transition-duration: 1s;
  transition-duration: 1s;
  /* Capability css-transitions is prefixed with -moz because 1.0075% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -moz context. */
  -moz-transition-timing-function: ease-in-out;
  /* Capability css-transitions is not prefixed with -ms because 0% of users are affected which is less than the threshold of 0.1. */
  /* Capability css-transitions is prefixed with -o because 0.14724% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -o context. */
  -o-transition-timing-function: ease-in-out;
  /* Capability css-transitions is prefixed with -webkit because 11.42224% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -webkit context. */
  -webkit-transition-timing-function: ease-in-out;
  transition-timing-function: ease-in-out;
  /* Capability transforms2d is prefixed with -moz because 1.35932% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -moz context. */
  -moz-transform: translate(0, 0);
  /* Capability transforms2d is prefixed with -ms because 4.62585% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -ms context. */
  -ms-transform: translate(0, 0);
  /* Capability transforms2d is prefixed with -o because 0.11279% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -o context. */
  -o-transform: translate(0, 0);
  /* Capability transforms2d is prefixed with -webkit because 49.72591% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -webkit context. */
  -webkit-transform: translate(0, 0);
  transform: translate(0, 0);
  content: "false"; }
  /* line 11, ../sass/prefixes.scss */
  div:hover {
    /* Capability transforms2d is prefixed with -moz because 1.35932% of users need it which is more than the threshold of 0.1%. */
    /* Creating new -moz context. */
    -moz-transform: translate(2em, 0);
    /* Capability transforms2d is prefixed with -ms because 4.62585% of users need it which is more than the threshold of 0.1%. */
    /* Creating new -ms context. */
    -ms-transform: translate(2em, 0);
    /* Capability transforms2d is prefixed with -o because 0.11279% of users need it which is more than the threshold of 0.1%. */
    /* Creating new -o context. */
    -o-transform: translate(2em, 0);
    /* Capability transforms2d is prefixed with -webkit because 49.72591% of users need it which is more than the threshold of 0.1%. */
    /* Creating new -webkit context. */
    -webkit-transform: translate(2em, 0);
    transform: translate(2em, 0); }
```

which looks good, although:
- I don't understand why browser-out-of-scope returns false, whatever the number version I pass into. Moreover,
- Changing safari minimum-version to version 7  and chrome to 26 changes nothing (the webkit prefix is still here but I would have supposed I'd be obsolete?)

But inside my current project using Bower + grunt, it turns to

``` css
@media -sass-debug-info {
  filename {
    font-family: file\:\/\/C\:\/dev\/New_Website\/website-js\/app\/styles\/prefixes\.scss;
  }

  line {
    font-family: \000036;
  }
}

div {
  /* Capability css-transitions is prefixed with -moz because 1.007496% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -moz context. */
  /* Capability css-transitions is not prefixed with -ms because 0% of users are affected which is less than the threshold of 0.1. */
  /* Capability css-transitions is prefixed with -o because 0.14724087% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -o context. */
  /* Capability css-transitions is prefixed with -webkit because 11.42224447% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -webkit context. */
  transition-property: transform;
  /* Capability css-transitions is prefixed with -moz because 1.007496% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -moz context. */
  /* Capability css-transitions is not prefixed with -ms because 0% of users are affected which is less than the threshold of 0.1. */
  /* Capability css-transitions is prefixed with -o because 0.14724087% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -o context. */
  /* Capability css-transitions is prefixed with -webkit because 11.42224447% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -webkit context. */
  transition-duration: 1s;
  /* Capability css-transitions is prefixed with -moz because 1.007496% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -moz context. */
  /* Capability css-transitions is not prefixed with -ms because 0% of users are affected which is less than the threshold of 0.1. */
  /* Capability css-transitions is prefixed with -o because 0.14724087% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -o context. */
  /* Capability css-transitions is prefixed with -webkit because 11.42224447% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -webkit context. */
  transition-timing-function: ease-in-out;
  /* Capability transforms2d is prefixed with -moz because 1.35932% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -moz context. */
  /* Capability transforms2d is prefixed with -ms because 4.62585% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -ms context. */
  /* Capability transforms2d is prefixed with -o because 0.112786% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -o context. */
  /* Capability transforms2d is prefixed with -webkit because 49.72590647% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -webkit context. */
  -webkit-transform: translate(0, 0);
  transform: translate(0, 0);
  content: "false";
}

@media -sass-debug-info {
  filename {
    font-family: file\:\/\/C\:\/dev\/New_Website\/website-js\/app\/styles\/prefixes\.scss;
  }

  line {
    font-family: \0000311;
  }
}

div:hover {
  /* Capability transforms2d is prefixed with -moz because 1.35932% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -moz context. */
  /* Capability transforms2d is prefixed with -ms because 4.62585% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -ms context. */
  /* Capability transforms2d is prefixed with -o because 0.112786% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -o context. */
  /* Capability transforms2d is prefixed with -webkit because 49.72590647% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -webkit context. */
  -webkit-transform: translate(2em, 0);
  transform: translate(2em, 0);
}
```

The comments are here, but they're empty. That really weird. 
I checked the versions, they're the same:
sass => "~>3.3.0.rc.4"
compass => "~>1.0.0.alpha.18"

Where could this difference come from?
