### ISSUE TITLE
Nested @media queries break "compressed" output in 1.0.0.alpha.18

### ISSUE THREAD

**Issue by chris-dura** [Compass/compass#1609]
Compass 1.0.0.alpha.18
Sass 3.3.1 (Maptastic Maple)

``` bash
compass compile --output-style compressed --force
```

It appears that having nested `@media` queries within rule blocks (which I think is at least a  _valid_ pattern, if not common), causes the output to seemingly have newlines added after the `@media` query, instead of having all the generated CSS on a single line.

``` css
.widget {
   color: red;
}

.gizmo {
   color: green;
}

@media (min-width: 960px) {
   .gizmo {
      color: blue;
   }
}

.doo-hickey {
   color: yellow;
}
```

The above output generates the expected single line CSS file:

``` css
.widget{color:red}.gizmo{color:green}@media (min-width: 960px){.gizmo{color:blue}}.doo-hickey{color:yellow}
```

However, nesting the `@media` within the `.gizmo` block correctly generates the same content, but with a newline after the `@media` query.

``` css

.widget {
   color: red;
}

.gizmo {
   color: green;
   @media (min-width: 960px) {
      color: blue;
   }
}

.doo-hickey {
   color: yellow;
}
```

output:

``` css
.widget{color:red}.gizmo{color:green}@media (min-width: 960px){.gizmo{color:blue}}
.doo-hickey{color:yellow}
```

**Comment by chris-dura** [comment]
Additional clarification... if there are several nested `@media` in the same rule, then the newline seems to be inserted only after the last one.

``` css

.widget {
   color: red;
}

.gizmo {
   color: green;
   @media (min-width: 960px) {
      color: blue;
   }
   @media (min-width: 1200px) {
      color: orange;
   }
}

.doo-hickey {
   color: yellow;
}
```

``` css
.widget{color:red}.gizmo{color:green}@media (min-width: 960px){.gizmo{color:blue}}@media (min-width: 1200px){.gizmo{color:orange}}
.doo-hickey{color:yellow}
```
