### ISSUE TITLE
bug in single-transition?

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#1614]
reported here https://github.com/chriseppstein/compass/issues/289#issuecomment-38145711 by @alkaithil.

**Comment by lencioni** [comment]
I just tried to reproduce the problem described by those comments in tests on top of 5e5b3dd4e99e66882be9506360a5e13b5967635e (currently latest master), 1.0.0.alpha.19, and 1.0.0.alpha.18 and was unable to reproduce the bug.

Specifically, I added this to core/test/integrations/projects/compass/sass/transition.scss

``` scss
.single-transform-transition-without-easing { @include single-transition(transform, 1s); }
```

And this to core/test/integrations/projects/compass/css/transition.css

``` css
.single-transform-transition-without-easing {
  -moz-transition: -moz-transform 1s;
  -o-transition: -o-transform 1s;
  -webkit-transition: -webkit-transform 1s;
  transition: transform 1s; }
```

And the tests passed.

@alkaithil and @lozandier is it possible that this has been resolved?
