### ISSUE TITLE
Compass sprite doesn't compile unless you call the sprite-map in a css prop

### ISSUE THREAD

**Issue by lifeiscontent** [Compass/compass#1628]
``` scss
@mixin sprite-image($name, $sprites, $sprites2x: null) {
  background-position: sprite-position($sprites, $name);
  width: image-width(sprite-file($sprites, $name));
  height: image-height(sprite-file($sprites, $name));
  @if $sprites2x {
    .hidpi & {
      $pos: sprite-position($sprites2x, $name);
      background-position: nth($pos, 1) / 2 nth($pos, 2) / 2;
      background-size: ceil(image-width(sprite-path($sprites2x)) / 2) auto;
    }
  }
}
```

if I use this mixin, I get errors saying the sprite-position function can't convert nil to a string.

however if I add `background-image: $sprite2x;` to the top of the `.hidpi` selector this works fine.

but I don't want to have to call the `$sprite` because its less optimal CSS output than I'd like to have.
