### ISSUE TITLE
idea: instead of mixins, use automagic properties

### ISSUE THREAD

**Issue by Silex** [Compass/compass#1637]
For example, the following code:

``` css
* {
  box-sizing: border-box;
}
```

has to be written currently like this:

``` css
* {
  @include box-sizing(border-box);
}
```

Which expands to:

``` css
* {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}
```

The current way is a bit annoying, in that it forces you to write "unstandard" css code using the mixin, and I don't really understand why this cannot be done automatically.

What prevents us from writing the following?

``` css
$automatically-do-mixin-for-box-sizing: true;

* {
  box-sizing: border-box;
}
```

Which would enable it that for each instance of `box-sizing`, the parser automatically uses the mixin for it, resulting in the same final css? That way we only write "standard" css and compass fills in the gaps.
