### ISSUE TITLE
support for sass 3.3 map objects?

### ISSUE THREAD

**Issue by dunn** [Compass/compass#1726]
Sass 3.3 was released four months ago, but I still can't get maps to work in Compass:

``` scss
$color:
    (ggg: #5f9ea0,
    ggb: #72a6c6,
    gbb: #7279c6,
    bbb: #635fa0,
    bbr: #9072c6,
    brr: #c672bd,
    rrr: #a05f8e);

    html {
        color: map-get($color, "ggg");
    }
```

This should compile to the following, and does when using `sass`:

``` css
html {
  color: cadetblue; }
```

But I get an error when trying to compile with compass.  Here's a link to the `--trace` for [`compass compile -e production --trace`](https://gist.github.com/grumble/1dbe4825eefeec080e36).
