### ISSUE TITLE
Rmove  the ruby path info in css file

### ISSUE THREAD

**Issue by chaoren1641** [Compass/compass#1734]
In our development team，some members useing Mac, some members using Windows，reset module always output ruby path info in css file

mac like this:

``` css
/* line 22, ../../../../../../../../Library/Ruby/Gems/2.0.0/gems/compass-0.12.7/frameworks/compass/stylesheets/compass/reset/_utilities.scss */
html {
  line-height: 1;
}
```

windows output like this:

``` css
/* line 22, c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/frameworks/compass/stylesheets/compass/reset/_utilities.scss */
html {
  line-height: 1;
}
```

this caused a file is always changing in git

how can this information does not output?

thanks!
