### ISSUE TITLE
Linear gradients generating with svg data URL even with $svg-gradient-shim-threshold: 100

### ISSUE THREAD

**Issue by alanhogan** [Compass/compass#1747]
**Renamed from …“even with $experimental-support-for-svg: false”**

Steps to reproduce:
1. Set <del>`$experimental-support-for-svg: false`</del> <ins>`$svg-gradient-shim-threshold: 100`</ins>
2. Import compass and/or compass/css3
3. Use `@include background` with a linear gradient

Expected: No data URI SVG background is output
Actual: SVG is generated and embedded

**Comment by eddie-ruva** [comment]
@alanhogan which version of compass are you using? maybe I can help you debug this problem.

**Comment by kemch** [comment]
I actually just started getting this behavior as well.
http://sassmeister.com/gist/4148026667ec7da09890

**Comment by eddie-ruva** [comment]
@kemch if you want to turn off the svg gradient generation you can set 

`$svg-gradient-shim-threshold: 100;` 

You can find more information about the configurable variables related to gradient in: http://beta.compass-style.org/reference/compass/css3/images/

**Comment by chriseppstein** [comment]
You should have got a deprecation warning about using `$experimental-support-for-svg` if you didn't that's a bug.

**Comment by alanhogan** [comment]
You’re totally right. I did get the warning. I’m sorry.

> WARNING: Compass has changed how browser support is configured. The following configuration variables are no longer supported: $experimental-support-for-svg.Details: http://compass-style.org/help/documentation/tuning-vendor-prefixes/

Will close. Apologies for wasting your time!

**Comment by alanhogan** [comment]
Thank you, @eddie-ruva. that’s what I wanted.

However, nothing seems to stop SVG output. 

When I set these insane values:

``` sass
$graceful-usage-threshold: 100
$critical-usage-threshold: 90
$svg-gradient-shim-threshold: 100
```

My output indeed loses `zoom: 1` and a ton of prefixed features, but the data-uri svg backgrounds are still included.

This happens for me in Compass `1.0.0.alpha.21` and still when I upgraded to `1.0.1`.

**Comment by chriseppstein** [comment]
have you declared explicit browser minimum support?

**Comment by alanhogan** [comment]
dang… yes. I thought it didn’t matter, but when I commented-out this line:

``` sass
$browser-minimum-versions: ((ie: '9'))
```

then suddenly the svg disappeared.

guh. sorry.

**Comment by chriseppstein** [comment]
right. svg would be required to support ie9 correctly... Is this a case where you don't want to support ie9 but just for this feature?

**Comment by alanhogan** [comment]
@chriseppstein That’s right. It’s not a big deal at all, really, but we have some buttons with multiple states and multiple gradients per state (generated content). It’s nice but not a “must”, and the SVGs are weightier than most cross-browser fixes. (The irony that I pushed for them to be included into Compass’ gradient support a few years ago isn’t lost on me, and I’m still glad they are there, I just… don’t need them for this project). I suppose they would probably gzip fairly well due to all the repetition of the SVG XML prologue. 

In sum, it’s not a big deal, it was just frustrating that I didn’t understand why I couldn’t seem to suppress them :/

**Comment by gmclelland** [comment]
Sorry, I don't fully understand.  How do I get rid of the backgrounds?

Right now it looks like:

```
background: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4gPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjUwJSIgeTE9IjAlIiB4Mj0iNTAlIiB5Mj0iMTAwJSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2Y3ZWVjMyIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iI2YxZTI5NyIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JhZCkiIC8+PC9zdmc+IA==');
```

I want to get rid of that but still support IE8+.

**Comment by verlok** [comment]
Same thing happens to me.
The thing I'd like to obtain from the following code...

``` scss
$graceful-usage-threshold: 5;
$critical-usage-threshold: 1;
@include background-image(linear-gradient(to bottom, white, #ccc));
```

...is just the following, so **without** the embedded SVG (and possibly without the old Safari fallback whenever it is or gets obsolete).

``` css
background-image: -moz-linear-gradient(top, #ffffff, #cccccc);
background-image: -webkit-linear-gradient(top, #ffffff, #cccccc);
background-image: linear-gradient(to bottom, #ffffff, #cccccc);
```

I tried to set different config variables, as reported in #1885, but I can't get this done.

Turning debug on using `$debug-browser-support: true;`, it appears that `$graceful-usage-threshold` and `$critical-usage-threshold` still have a value of 0.1 even if I tried to change it.

**Comment by verlok** [comment]
EUREKA!!! 
I've reached the solution!!!

The values of the [configurable variables for images](http://beta.compass-style.org/reference/compass/css3/images/) `$gradient-support-threshold`, `$svg-gradient-shim-threshold` and `$owg-threshold` are copied from the configuration variable `$graceful-usage-threshold` when Compass is imported, so if you want a different value for them, **you have to define `$graceful-usage-threshold` before importing Compass**.

So the following SCSS...

``` scss
// DEFINE BEFORE IMPORTING COMPASS
$graceful-usage-threshold: 5;
$critical-usage-threshold: 1;

@import "compass";

.test {
  @include background-image(linear-gradient(to bottom, white, black));
}
```

...produces this CSS:

``` css
.test {
  background-image: -webkit-linear-gradient(top, #ffffff, #000000);
  background-image: linear-gradient(to bottom, #ffffff, #000000);
}
```

Whereas the following SCSS...

``` scss
// DEFINE AFTER IMPORTING COMPASS
@import "compass";

$graceful-usage-threshold: 5;
$critical-usage-threshold: 1;

.test {
  @include background-image(linear-gradient(to bottom, white, black));
}
```

...produces this (heavy) CSS:

``` css
.test {
  background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4gPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkIiBncmFkaWVudFVuaXRzPSJvYmplY3RCb3VuZGluZ0JveCIgeDE9IjAuNSIgeTE9IjAuMCIgeDI9IjAuNSIgeTI9IjEuMCI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2ZmZmZmZiIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzAwMDAwMCIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JhZCkiIC8+PC9zdmc+IA==');
  background-size: 100%;
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #ffffff), color-stop(100%, #000000));
  background-image: -moz-linear-gradient(top, #ffffff, #000000);
  background-image: -webkit-linear-gradient(top, #ffffff, #000000);
  background-image: linear-gradient(to bottom, #ffffff, #000000);
}
```
