### ISSUE TITLE
Undefined mixin 'experimental'

### ISSUE THREAD

**Issue by kevinsalter** [Compass/compass#1798]
calling `@import "compass/css3/transition"` in a SCSS file doesn't work.  Instead it throws the error `Undefined mixin 'experimental'`

**Comment by eddie-ruva** [comment]
@KevinSalter which version of compass are you using? 

I tried to reproduce your problem with the following sass file

``` sass

@import compass/css3/transition

#width
  +transition-property(width)
```

``` bash
$ compass -v
Compass 1.0.1 (Polaris)

$ sass -v
Sass 3.4.2 (Selective Steve)
```

**Comment by kevinsalter** [comment]
@eddie-ruva I'm also using `Compass 1.0.1 (Polaris)` and `Sass 3.4.2 (Selective Steve)`

I believe the difference is that I'm calling `experimental` directly, as in the example below.  Previously this worked fine.  Has this kind of access been deprecated, maybe?

This example was generated with `compass create sass-test` and then adding the following code to the `screen.scss`

``` scss
@import "compass/reset";
@import "compass/css3/transition";

$color: black;
$opacity: .8;
$duration: 3s;

.sample-class {
  background: $color;
  @include experimental(animation-duration, $duration * 2);
  opacity: $opacity;
}
```

This throws the following exception in the terminal:

```
modified sass-test/sass/screen.scss
    error sass-test/sass/screen.scss (Line 15: Undefined mixin 'experimental'.)
```
