### ISSUE TITLE
      background: linear-gradient(); Being over written on output

### ISSUE THREAD

**Issue by doodirock** [Compass/compass#1815]
I've seen issues on this in the past, but not sure how to solve it.  I want to create a simple faded line.  When I write my css as is:

```
background: linear-gradient(0 0, 100% 0, from(rgba(255, 255, 255, 0)), to(rgba(255, 255, 255, 0)), color-stop(25%, #d65925), color-stop(75%, #d65925));
```

However the output is overwritten as:

```
background: linear-gradient(0 0,100% 0,left,right,color-stop(25%,#d65925),color-stop(75%,#d65925));
```

Whats the best way to handle this use case?

**Comment by eddie-ruva** [comment]
Hi @doodirock I'm trying to understand what you want to do with this linear gradient to see if I can help you. I think the syntax is wrong because _linear-gradient_ takes a position which can be an angle or a keyword such as (to top, to bottom, to right, to left) and after that a list of color stops. You can find some examples here: http://compass-style.org/examples/compass/css3/gradient/

I think for the gradient that you are trying to define the right way to use the function would be:

``` scss
.class {
    @include background(linear-gradient(to top, rgba(255, 255, 255, 0) 0%, #d65925 25%, #d65925 75%, rgba(255, 255, 255, 0) 100%));
}
```

I'll be glad to help you if this was not the right solution to get to the gradient that you want to define.

**Comment by doodirock** [comment]
This is basically what I'm trying to build eddie.  Thanks so much for the help.

**Comment by eddie-ruva** [comment]
@doodirock Glad I was able to help!

**Comment by doodirock** [comment]
Just realized I didnt link my codepen 

http://codepen.io/jared-christensen/pen/wlhzy

This seem about right in terms of what im going for?

**Comment by eddie-ruva** [comment]
@doodirock  For that I think you can use: 

``` scss
@import "compass/css3/_images";

hr {
  height: 1px;
  margin: 50px 0;
  @include background(linear-gradient(left, rgba(0,0,0,0), #333333, rgba(0,0,0,0)));
  border: 0;
}
hr:after { 
  display: block; 
  content:'';
  height: 30px;
  @include background(radial-gradient(farthest-side at center top, #cccccc 0%, rgba(255, 255, 255, 0) 100%));
}

```
