### ISSUE TITLE
"List index is 2 but list is only 1 item long for `nth'" in `intersect-browser-ranges()`

### ISSUE THREAD

**Issue by mirisuzanne** [Compass/compass#1853]
To reproduce:

``` scss
// An actual use-case that demonstrates the problem
.use-case {
  @include with-browser-ranges(css-mediaqueries) {
    @include background-image(linear-gradient(red, blue));
  }
}

// A simplification of the issue
$ranges: (ie: "9" "11");
$new-ranges: (ie: "9");
@debug intersect-browser-ranges($ranges, $new-ranges);
```

At some point in the use-case, `(ie: "9", opera: "9.5-9.6")` is passed into `intersect-browser-ranges()` for the `$new-ranges` argument. The error comes from the single version number. Is that a mistake, or an edge-case that `intersect-browser-ranges` should support?

If the latter, I can submit a patch:

``` scss
// support.scss line 280
// we may need to to the same for line 278 ($old-max)?
$new-max: if(length($new-range) > 1, nth($new-range, 2), $new-min);
```

This is the cause of ericam/susy#395
