### ISSUE TITLE
Compass Cross-Browser Support Configuration not working

### ISSUE THREAD

**Issue by verlok** [Compass/compass#1885]
Hi guys,
I've noticed that every time that I use a gradient as a background, e.g. with the following:

``` scss
.foo {
    @include background-image(linear-gradient(to right, black, white));
}
```

Compass generates a big amount of CSS, this:

``` css
.foo {
  background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4gPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkIiBncmFkaWVudFVuaXRzPSJvYmplY3RCb3VuZGluZ0JveCIgeDE9IjAuMCIgeTE9IjAuNSIgeDI9IjEuMCIgeTI9IjAuNSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzAwMDAwMCIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iI2ZmZmZmZiIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JhZCkiIC8+PC9zdmc+IA==');
  background-size: 100%;
  background-image: -webkit-gradient(linear, 0% 50%, 100% 50%, color-stop(0%, #000000), color-stop(100%, #ffffff));
  background-image: -moz-linear-gradient(left, #000000, #ffffff);
  background-image: -webkit-linear-gradient(left, #000000, #ffffff);
  background-image: linear-gradient(to right, #000000, #ffffff);
}
```

So I mainly want to remove the embedded SVG.

I've searched in the articles [Tuning Vendor Prefixes from Compass Stylesheets](http://compass-style.org/help/documentation/tuning-vendor-prefixes/) and [Compass Cross-Browser Support Configuration](http://compass-style.org/reference/compass/support/) and so I tried to do so:

``` scss
@import "compass/css3";

$graceful-usage-threshold: 100; //don't support anything that graceful degrades
$critical-usage-threshold: 100; //don't support anything that will break layouts in older browsers

.foo {
    @include background-image(linear-gradient(to right, black, white));
}
```

But the output CSS is always the same, no matter what value I give to the `$graceful-usage-threshold` and `$critical-usage-threshold` variables.

I've also already searched on Google and I didn't found anything that explains how to propery set those variables.

Can you help?
Thank you very much in advance

**Comment by verlok** [comment]
I did another test using `$debug-browser-support: true` so that I could read the reason in the comments, but while the `$debug-browser-support` variable seems to be considered, the `$graceful-usage-threshold` and `$critical-usage-threshold` variables seem to be ignored.

Here's the scss code I have:

``` scss
@import "compass/css3";
@import "compass/support";

$graceful-usage-threshold: 0.333;
$critical-usage-threshold: 0.666;
$debug-browser-support: true;
$browser-minimum-versions: ("chrome": null, "firefox": "4", "ie": "8", "safari": "6", "opera": "16");

.square {
    width: 200px;
    height: 200px;
    @include background-image(linear-gradient(to bottom, white, #ccc));
}
```

And the css code I get.

``` css
.square {
  width: 200px;
  height: 200px;
  /* Content for ie 9.
  Min version: 8.
  User threshold to keep: 0.1%. If ie 9 are omitted: 2.6001%. */
  /* Creating new -svg context. */
  background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4gPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkIiBncmFkaWVudFVuaXRzPSJvYmplY3RCb3VuZGluZ0JveCIgeDE9IjAuNSIgeTE9IjAuMCIgeDI9IjAuNSIgeTI9IjEuMCI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2ZmZmZmZiIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iI2NjY2NjYyIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JhZCkiIC8+PC9zdmc+IA==');
  background-size: 100%;
  /* Content for android 2.1 - 3.
  Min version: unspecified.
  User threshold to keep: 0.1%. If android 2.1 - 3 are omitted: 1.11224%. */
  /* Creating new -owg context. */
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #ffffff), color-stop(100%, #cccccc));
  /* Capability css-gradients is prefixed with -moz because 0.75106% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -moz context. */
  background-image: -moz-linear-gradient(top, #ffffff, #cccccc);
  /* Capability css-gradients is not prefixed with -ms because 0% of users are affected which is less than the threshold of 0.1. */
  /* Capability css-gradients is not prefixed with -o because 0.07115% of users are affected which is less than the threshold of 0.1. */
  /* Capability css-gradients is prefixed with -webkit because 9.61489% of users need it which is more than the threshold of 0.1%. */
  /* Creating new -webkit context. */
  background-image: -webkit-linear-gradient(top, #ffffff, #cccccc);
  background-image: linear-gradient(to bottom, #ffffff, #cccccc);
}
```

Why debug info still tells me that the user threshold to keep is 0.1%?

More information about my versions:

Compass version: 1.0.1 
Sass version: Sass 3.4.5 then Sass 3.4.9 (I tried both)
Ruby version: ruby 1.9.3p551 (2014-11-13) [i386-mingw32]
OS: Windows 7

**Comment by eddie-ruva** [comment]
@verlok I believe the svg is still in the output because your minimum browser version for ie is version 8 so it needs the svg to support it correctly. Maybe this issue could help you [1747](https://github.com/Compass/compass/issues/1747).

**Comment by verlok** [comment]
Hi,
of course I want to support IE8, but with graceful degradation...

The result that I want to get is a gradient that works only in IE9 or IE10,
with a solid color background in older versions of IE, but I don't want to
change other behaviors of Compass that might depend on that configuration
for legacy browser versions.

I get confused about how the threshold variables work in conjunction with
the browser support array. :-/

**Comment by verlok** [comment]
In other words, how does `$browser-minimum-versions` works along with `$graceful-usage-threshold` and/or `$critical-usage-threshold` variables?

Shouldn't `$graceful-usage-threshold` and/or `$critical-usage-threshold` variables do the same thing of `$browser-minimum-versions`, but using data from caniuse.com instead of letting me manually choose?

Apparently the `$graceful-usage-threshold` and/or `$critical-usage-threshold` I set in my SCSS files simply get ignored.

**Comment by verlok** [comment]
EUREKA!!! 
I've reached the solution!!!

The values of the [configurable variables for images](http://beta.compass-style.org/reference/compass/css3/images/) `$gradient-support-threshold`, `$svg-gradient-shim-threshold` and `$owg-threshold` are copied from the configuration variable `$graceful-usage-threshold` when Compass is imported, so if you want a different value for them, **you have to define `$graceful-usage-threshold` before importing Compass**.

So the following SCSS...

``` scss
// DEFINE BEFORE IMPORTING COMPASS
$graceful-usage-threshold: 5;
$critical-usage-threshold: 1;

@import "compass";

.test {
  @include background-image(linear-gradient(to bottom, white, black));
}
```

...produces this CSS:

``` css
.test {
  background-image: -webkit-linear-gradient(top, #ffffff, #000000);
  background-image: linear-gradient(to bottom, #ffffff, #000000);
}
```

Whereas the following SCSS...

``` scss
// DEFINE AFTER IMPORTING COMPASS
@import "compass";

$graceful-usage-threshold: 5;
$critical-usage-threshold: 1;

.test {
  @include background-image(linear-gradient(to bottom, white, black));
}
```

...produces this (heavy) CSS:

``` css
.test {
  background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4gPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkIiBncmFkaWVudFVuaXRzPSJvYmplY3RCb3VuZGluZ0JveCIgeDE9IjAuNSIgeTE9IjAuMCIgeDI9IjAuNSIgeTI9IjEuMCI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2ZmZmZmZiIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzAwMDAwMCIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JhZCkiIC8+PC9zdmc+IA==');
  background-size: 100%;
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #ffffff), color-stop(100%, #000000));
  background-image: -moz-linear-gradient(top, #ffffff, #000000);
  background-image: -webkit-linear-gradient(top, #ffffff, #000000);
  background-image: linear-gradient(to bottom, #ffffff, #000000);
}
```
