### ISSUE TITLE
Animations keyframe mixin isn't outputting the set animation name in the CSS file. 

### ISSUE THREAD

**Issue by rpkoller** [Compass/compass#1897]
With the install of Yosemite i was finally able to upgrade from Compass 0.12.x to Compass 1.0.1. At the moment i am in order of getting my projects running on the newer plugins. In one of my projects i am using an animation and somehow it isn't working at all. I've built a stripped down sample case on Codepen with the mixins I use in my project.

http://codepen.io/rpkoller/pen/qEZZPp

Everything works fine there. Then I've ported the same code to my local environment and let Codekit and the external Compass gem do the compiling ( the set up i am regularly using):

https://dl.dropboxusercontent.com/u/8578/anims.zip

If i check the CSS output as well as in the browser everything works and is fine. But when i try in the scope of my whole project the issue turns up. I have a partial file called _animations.scss . 

``` scss
@include keyframes(box-up) {
    0% {
        height:30%;
    }
    100% {
        height:100%;
    }
}

.xxxx {
    background: red;
}
```

i've added the .xxxx class to see if the partial is properly imported. Later on in another partial the animation mixin is called for a hover pseudo class: 

``` scss
.fp-bb {
    &:hover {
        @include animation(box-up 1s);
        height:100%;
        overflow:hidden;
    }   

    &:hover .fp-pro-excerpt {
        display:block;
    }

    .fp-pro-excerpt {
        display:none;
    }
}
```

The CSS output for the animation mixin snippet looks correct: 

``` css
.fp-bb:hover {
  -webkit-animation: box-up 1s;
  -ms-animation: box-up 1s;
  animation: box-up 1s;
  height: 100%;
  overflow: hidden; }
.fp-bb:hover .fp-pro-excerpt {
  display: block; }
.fp-bb .fp-pro-excerpt {
  display: none; }
```

But the keyframes part differs: 

``` css
@-webkit-keyframes $animation-name {
  0% {
    height: 30%; }
  100% {
    height: 100%; } }
@-ms-keyframes $animation-name {
  0% {
    height: 30%; }
  100% {
    height: 100%; } }
@keyframes $animation-name {
  0% {
    height: 30%; }
  100% {
    height: 100%; } }
.xxxx {
  background: red; }
```

Are there certain circumstances that lead to such a strange behaviour using the $animation-name variable instead of the given animation name? Is that bug or a misusage on my side? Best regards Ralf
