### ISSUE TITLE
transition() is phantom calling "remove()"

### ISSUE THREAD

**Issue by mattdrose** [Compass/compass#1931]
This is a strange bug.

I'm using a remove() function [that can be seen here](https://github.com/carpages/gemini-css/blob/master/functions/_lists.scss).

``` scss
@function remove($list, $value, $recursive: false) {
  $result: ();

  @for $i from 1 through length($list) {
    @if type-of(nth($list, $i)) == list and $recursive {
      $result: append($result, remove(nth($list, $i), $value, $recursive));
    }

    @else if nth($list, $i) != $value {
      $result: append($result, nth($list, $i));
    }
  }

  @return $result;
}
```

When I call `transition()` in a separate file, specifically `@include transition(opacity .25s ease);`, I get the error: `Line 24 of bower_components/gemini-css/functions/_lists.scss: List index is 1 but list has no items for `nth'`. [This is a link to the `_lists.scss` file.](https://github.com/carpages/gemini-css/blob/master/functions/_lists.scss)

Here is the full trace:

```
Error: List index is 1 but list has no items for `nth'
on line 25 of /var/www/dev/repos/gemini/gemini-modules/gemini-tooltip/bower_components/gemini-css/functions/_lists.scss, in `@content'
from line 227 of /usr/local/rvm/gems/ruby-2.1.4/gems/compass-core-1.0.3/stylesheets/compass/_support.scss, in `@content'
from line 312 of /usr/local/rvm/gems/ruby-2.1.4/gems/compass-core-1.0.3/stylesheets/compass/_support.scss, in `with-browser-ranges'
from line 226 of /usr/local/rvm/gems/ruby-2.1.4/gems/compass-core-1.0.3/stylesheets/compass/_support.scss, in `@content'
from line 198 of /usr/local/rvm/gems/ruby-2.1.4/gems/compass-core-1.0.3/stylesheets/compass/_support.scss, in `with-prefix'
from line 225 of /usr/local/rvm/gems/ruby-2.1.4/gems/compass-core-1.0.3/stylesheets/compass/_support.scss, in `with-each-prefix'
from line 147 of /usr/local/rvm/gems/ruby-2.1.4/gems/compass-core-1.0.3/stylesheets/compass/css3/_transition.scss, in `transition'
from line 24 of /var/www/dev/repos/gemini/gemini-modules/gemini-tooltip/sass/tooltip.scss
from line 3 of /var/www/dev/repos/gemini/gemini-modules/gemini-tooltip/test/gemini-tooltip.test.scss
```

When I debug that line, it seems that `transition()` is some how calling `remove()` and passing "()" as the first parameter.

I'm on Compass 1.0.3.

Any ideas?

**Comment by cimmanon** [comment]
I cannot reproduce the error.  The following code compiles exactly as expected:

``` scss
@import "compass/css3/transition";

@function remove($list, $value, $recursive: false) {
  $result: ();

  @for $i from 1 through length($list) {
    @if type-of(nth($list, $i)) == list and $recursive {
      $result: append($result, remove(nth($list, $i), $value, $recursive));
    }

    @else if nth($list, $i) != $value {
      $result: append($result, nth($list, $i));
    }
  }

  @return $result;
}

.foo {
    @include transition(opacity .25s ease);
}
```
