### ISSUE TITLE
debug-vertical-alignment should provide option for using `!important`

### ISSUE THREAD

**Issue by mxdubois** [Compass/compass#1953]
I frequently want to display a grid background on a container that has a background set somewhere else in the codebase. It'd be nice if I could force the `debug-vertical-alignment` mixin to place `!important` on all the `background-image` properties.

Specific example:

``` scss
@mixin grid-container {
  /* ...props redacted... */
  &.debug-vr {
    @include debug-vertical-alignment;
  }
}

body {
  @include grid-container;
  &.foobar {
    background: red;
  }
}
```
