### ISSUE TITLE
Optimize sprite css output

### ISSUE THREAD

**Issue by liorocks** [Compass/compass#1969]
Hello,

I have a suggestion to optimize CSS output of sprite generated files.

Consider the following scenario.
In our `/images/icon/` directory we have a bunch of `.png` files/icons. 
And we have `_icons.scss` file, contains the following code:

``` sass
$icon-sprite-dimensions: true;
$icon-layout: smart;
$icon-sprite-base-class: '.icon';
@import "icon/*.png";
@include all-icon-sprites;

.icon {
  display: inline-block;
  vertical-align: middle;
}

```

If we compile this compass file, the css output will be something like this:

``` css
.icon, .icon-cart, .icon-home {
  background-image: url('../images/icon-s0a7bc27549.png');
  background-repeat: no-repeat;
}
```

And the list of CSS class names/selectors of icons will increase every time, when new icon is added.
It would be so much better, if it could render the "starts with" or "contains" css syntax:

"Starts with"

``` css
[class^="icon-"] {
  background-image: url('../images/icon-s0a7bc27549.png');
  background-repeat: no-repeat;
}
```

"Contains" 

``` css
[class*="icon-"] {
  background-image: url('../images/icon-s0a7bc27549.png');
  background-repeat: no-repeat;
}
```

This kind of syntax is supported in every major browser, including IE7 and above: http://caniuse.com/#feat=css-sel3

I, personally don't know Ruby, otherwise I would send a pull request.  
Please, anyone, if you think that, this is a better way and knows how to improve it, make a change, send a pull request.

Thanks!

**Comment by liorocks** [comment]
Ok, I was able to do the following:

To remove all extra CSS classes, for example:
 .icon-cart, .icon-home, .... and etc

In this file https://github.com/Compass/compass/blob/stable/core/stylesheets/compass/utilities/sprites/_base.scss we can comment/remove the 85 line:

``` sass
@if $base-class { @extend #{$base-class}; }
```

Then it will just generate:

``` css
.icon {
  background-image: url('../images/icon-s0a7bc27549.png');
  background-repeat: no-repeat;
}
```

To change the `.icon` to the "contains syntax" `[class*="icon-"]`:
We have to change in this file, on line 50: https://github.com/Compass/compass/blob/stable/cli/lib/compass/sprite_importer/content.erb#L50

This code:

``` sass
#{$<%= name %>-sprite-base-class} {
```

to this:

``` sass
[class*="#{$<%= name %>-sprite-base-class}-"] {
```

But, in this case, we have to use in our `_icons.scss` file the following:

``` sass
$icon-sprite-base-class: 'icon';
```
