### ISSUE TITLE
Mix :nested and :compact output style

### ISSUE THREAD

**Issue by fileboxxx** [Compass/compass#1991]
I believe that It should be very nice to mix these two output options to produce formating similar to the following:

``` css
.wrapper {width: 80%; margin: 0 auto;}
    .wrapper p {line-height: 2.4;}
        .wrapper p a {text-decoration: none;}
```

instead of just :nesting, which looks like:

``` css
.wrapper {
    width: 80%;
    margin: 0 auto;}
    .wrapper p {
        line-height: 2.4;}
        .wrapper p a {
            text-decoration: none;}
```

or just :compact

``` css
.wrapper { width: 80%; margin: 0 auto; }
.wrapper p { line-height: 2.4; }
.wrapper p a { text-decoration: none; }
```

is it possible ?
