### ISSUE TITLE
Need color value convert tool

### ISSUE THREAD

**Issue by qakcn** [Compass/compass#2038]
On Page: http://compass-style.org/reference/compass/helpers/colors/

Mostly, lack of this function doesn't bother me. But when I want color with alpha channel, it's better to have this.

For example: 
`hex2rgba(#fff, 0.6)` returns `rgba(255, 255, 255, 0.6)`
`name2hsla(dodgerblue, 0.3)` returns `hsla(210, 100%, 56%, 0.3)`

**Comment by cimmanon** [comment]
Vanilla Sass already provides the rgba function for this purpose.

``` scss
.foo {
    color: rgba(#fff, 0.6); 
    color: rgba(dodgerblue, 0.3);
}
```

Output:

``` css
.foo {
  color: rgba(255, 255, 255, 0.6);
  color: rgba(30, 144, 255, 0.3);
}
```
