### ISSUE TITLE
Add support for variables within @media rules

### ISSUE THREAD

**Issue by thulstrup** [Compass/compass#380]
It would be great to be able to do something like this:

``` css
$min: 480px;
$max: 768px;
@media only screen {
  @media (min-width: $min) {
    // ...
  }
  @media (min-width: $min) and (max-width: $max) {
    // ...
  }
}
```
