### ISSUE TITLE
Error when importing "icon/*.png"

### ISSUE THREAD

**Issue by Zettersten** [Compass/compass#396]
I am trying to follow the tutorial here: http://compass-style.org/help/tutorials/spriting/

My code: 

``` css
@import "icon/*.png";
@include all-icon-sprites;

#logo {
    @extend .floatLeft;
    margin:0 20px 10px;
    a {
        @extend .blank;
        display: block;
        height: 69px;
        width: 165px;
    }
}
```

It should spit out all the items i have in my icon folder. Instead I get the following error...

error main/public/includes/sass/imports/header.scss (Line 16: Invalid CSS after "...p("icon/*.png",": expected function argument, was ");")
### Note: the end of #logo is line 16.

My versions,

Sass version: Sass 3.2.0.alpha.4 (Bleeding Edge)
Haml version: Haml 3.2.0.alpha.3 (Bleeding Edge)
Ruby version: Ruby 1.8.7
