### ISSUE TITLE
Undefined mixin all-icon-sprites

### ISSUE THREAD

**Issue by AndreasMadsen** [Compass/compass#403]
Hey
Well i don not have much experience with compass, but i get this error:
Undefined mixin 'all-icon-sprites'
When i search the reason is that people use the wrong folder name, but this is not the case.

My config.rb looks like this:

``` ruby
http_path = "/"
css_dir = "CSS"
sass_dir = "SASS"
images_dir = "IMG"
javascripts_dir = "JS"
output_style = :expanded
```

And my file structure is:
/
- /IMG
  | - /sprite
     | - RSS.png
     | - login.png
     | - search.png
     | - print.png
- /CSS
  | test.scss
- /SASS
  | test.scss
- /JS

The content of test.scss is:

``` CSS
@import "sprite/*.png";
@include all-icon-sprites;
```

When i try to compile I get this error:
error /SASS/test.scss (Line 2: Undefined mixin 'all-icon-sprites'.)
overwrite /CSS/test.css 

The funny thing is that in /IMG there is now a file called: sprite-5e26b99297.png
and it contain all the files in /IMG/sprite

The content of test.css is:

``` CSS
/*
Syntax error: Undefined mixin 'all-icon-sprites'.
        on line 2 of /Users/Andreas/Sites/NetKogeren/SASS/test.scss, in `all-icon-sprites'
        from line 2 of /Users/Andreas/Sites/NetKogeren/SASS/test.scss

1: /Users/Andreas/Sites/NetKogeren/SASS/test.scss

Backtrace:
/Users/Andreas/Sites/NetKogeren/SASS/test.scss:2:in `all-icon-sprites'
/Users/Andreas/Sites/NetKogeren/SASS/test.scss:2
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/perform.rb:169:in `visit_mixin'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/base.rb:53:in `map'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/perform.rb:27:in `visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/perform.rb:39:in `with_environment'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/perform.rb:26:in `visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/perform.rb:47:in `visit_root'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/perform.rb:7:in `send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/visitors/perform.rb:7:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/tree/root_node.rb:20:in `render'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/engine.rb:291:in `_render'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/engine.rb:239:in `render'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/util.rb:298:in `silence_sass_warnings'
/Library/Ruby/Gems/1.8/gems/sass-3.1.1/lib/sass/../sass/engine.rb:239:in `render'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/compiler.rb:130:in `compile'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/compiler.rb:116:in `timed'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/compiler.rb:129:in `compile'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/logger.rb:45:in `red'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/compiler.rb:128:in `compile'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/compiler.rb:108:in `compile_if_required'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/compiler.rb:95:in `run'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/compiler.rb:93:in `each'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/compiler.rb:93:in `run'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/compiler.rb:116:in `timed'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/compiler.rb:92:in `run'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/commands/watch_project.rb:142:in `recompile'
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `to_proc'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/path.rb:73:in `call'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/path.rb:73:in `run_callback'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/path.rb:55:in `callback_action'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/path.rb:35:in `update'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/state/directory.rb:39:in `modified'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/state/directory.rb:37:in `each'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/state/directory.rb:37:in `modified'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/state/directory.rb:18:in `refresh'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/backends/fsevents.rb:15:in `add_handler'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/backends/fsevents.rb:14:in `each'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/backends/fsevents.rb:14:in `add_handler'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/backends/rubycocoa/fsevents.rb:107:in `call'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/backends/rubycocoa/fsevents.rb:107:in `initialize'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/backends/fsevents.rb:27:in `call'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/backends/fsevents.rb:27:in `CFRunLoopRun'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/backends/fsevents.rb:27:in `run'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/monitor.rb:26:in `run'
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm.rb:20:in `monitor'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/commands/watch_project.rb:86:in `perform'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/commands/base.rb:18:in `execute'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/commands/project_base.rb:19:in `execute'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/exec/sub_command_ui.rb:15:in `run!'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/bin/compass:25
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/bin/compass:39:in `call'
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/bin/compass:39
/usr/bin/compass:19:in `load'
/usr/bin/compass:19
*/
body:before {
  white-space: pre;
  font-family: monospace;
  content: "Syntax error: Undefined mixin 'all-icon-sprites'.\A         on line 2 of /Users/Andreas/Sites/NetKogeren/SASS/test.scss, in `all-icon-sprites'\A         from line 2 of /Users/Andreas/Sites/NetKogeren/SASS/test.scss\A \A 1: /Users/Andreas/Sites/NetKogeren/SASS/test.scss"; }
```
