### ISSUE TITLE
Sprites url in rails 3.1 doesn't work with assets dir

### ISSUE THREAD

**Issue by Godisemo** [Compass/compass#463]
The spritemap in rails 3.1 is generated to the assets folder but the css output is something like

``` css
.layout-sprite { background: url(/images/layout-xxx.png); }
```

to work with the assets folder it should be something like

``` css
.layout-sprite { background: url(layout-xxx.png); }
```
