### ISSUE TITLE
Sprite helper magic icon-sprite mixin doesn't work for pseudo-class selectors

### ISSUE THREAD

**Issue by markoan** [Compass/compass#480]
I started using the sprite helper for a custom menu I made and I wanted to optimize sprite size (avoiding extra space padding in the images). I found a way to insert an element using the :before pseudo-class and styling that element with the size of my sprites. The problem is that compass doesn't recognize the special class and uses the complete selector thus generating incorrect css for the element.

For example:

``` css
li.menu-item-43 a:before { @include icon-sprite(mail) }
```

Should generate:

``` css
#header #app-container nav.nav-featured ul li.menu-item-43 a:hover:before {
  background-position: 0 -96px;
}
```

But instead generates:

``` css
#header #app-container nav.nav-featured ul li.menu-item-43 a:before:hover {
  background-position: 0 -96px;
}
```

BTW, I believe it would be a great idea to work on an additional helper that uses this pseudo-class the same way I did to automatically add icons to menus. It could even have options for icons on left and icons on top.
