### ISSUE TITLE
sprockets and sprites (rails 3.1)

### ISSUE THREAD

**Issue by evansagge** [Compass/compass#513]
I have this defined in app/assets/stylesheets/icons.css.scss

``` scss
@import "compass/utilities/sprites";

$icons-spacing: 20px;
$icons-position: 0% !default;
$icons-repeat: no-repeat !default;
$icons-sprite-dimensions: true !default;

@import "icons/*.png";

.add_icon { @include icons-sprite(add) }
.edit_icon { @include icons-sprite(pencil) }
.delete_icon { @include icons-sprite(delete) }
.check_icon { @include icons-sprite(tick) }
.cancel_icon { @include icons-sprite(cross) }
.warning_icon { @include icons-sprite(warning) }
.error_icon { @include icons-sprite(error) }
.info_icon { @include icons-sprite(info) }
.query_icon { @include icons-sprite(query) }
```

In development mode, this works fine. I get an `icons-s17f1c1a7aa.png` generated in app/assets/images/, and the icons show up fine when I use them.

But when I deploy with sprockets, it renames the generated sprite to something like `icons-s17f1c1a7aa-c8a6d4369227ac689dc8f40706521d68.png`, but the background-image used by the generated css from above still references `icons-s17f1c1a7aa.png`.

Is there any solution to this yet?
