### ISSUE TITLE
nested-reset mixin cannot reset font properties.

### ISSUE THREAD

**Issue by Phize** [Compass/compass#580]
nested-reset mixin cannot reset font properties (and text-\* properties).

Compass Reset Utilities: https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/reset/_utilities.scss

Here is a test code.

``` html
<div class="test">
    <p>.test { font-weight: bold; }</p>
    <div class="nested-reset">
        <p>.nested-reset { @include nested-reset; }</p>
    </div>
</div>
```

``` css
@import 'compass/reset';
.test { font-weight: bold; }
.nested-reset { @include nested-reset; }
```

Live demo: http://jsfiddle.net/6cYfz/1/

I added some lines to reset font-style/variant/weight although it is a matter of personal preference.

``` css
@mixin nested-reset {
  font-style: normal;
  font-variant: normal;
  font-weight: normal;

  div, span, applet, object, iframe,
  h1, h2, h3, h4, h5, h6, p, blockquote, pre,
  a, abbr, acronym, address, big, cite, code,
  del, dfn, em, img, ins, kbd, q, s, samp,
  small, strike, strong, sub, sup, tt, var,
  b, u, i, center,
  dl, dt, dd, ol, ul, li,
  fieldset, form, label, legend,
  table, caption, tbody, tfoot, thead, tr, th, td,
  article, aside, canvas, details, embed, 
  figure, figcaption, footer, header, hgroup, 
  menu, nav, output, ruby, section, summary,
  time, mark, audio, video {
    @include reset-box-model;
    @include reset-font; }
  table {
    @include reset-table; }
  caption, th, td {
    @include reset-table-cell; }
  q, blockquote {
    @include reset-quotation; }
  a img {
    @include reset-image-anchor-border; } }
```
