### ISSUE TITLE
sass-rails and compass *_url helpers conflict

### ISSUE THREAD

**Issue by agibralter** [Compass/compass#630]
Both sass-rails and compass define Sass helper functions with the same names:

https://github.com/rails/sass-rails/blob/master/lib/sass/rails/helpers.rb#L29-35
https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/urls.rb#L24-49

Are they meant to be able to work together? Is there any point in having the two together?

**Comment by scottdavis** [comment]
One overrides the other this is on purpose

**Comment by agibralter** [comment]
@scottdavis -- which overrides which? I'm trying to use `font-url(..., true)` but `rake assets:precompile` is telling me `wrong number of arguments (2 for 1) for 'font-url'`

**Comment by agibralter** [comment]
Basically I was trying to end up with:

``` css
@font-face {
    font-family: 'ChunkFiveRegular';
    src: url('Chunkfive-webfont.eot');
    src: url('Chunkfive-webfont.eot?#iefix') format('embedded-opentype'),
         url('Chunkfive-webfont.woff') format('woff'),
         url('Chunkfive-webfont.ttf') format('truetype'),
         url('Chunkfive-webfont.svg#ChunkFiveRegular') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

Using **sass-rails** helpers (apparently that's what seems to have priority), I was able to achieve that by doing:

``` scss
@font-face {
  font-family: 'ChunkFiveRegular';
  src: url(font-path('Chunkfive-webfont.eot'));
  src: url(font-path('Chunkfive-webfont.eot') + '?#iefix') format('embedded-opentype'),
       url(font-path('Chunkfive-webfont.woff')) format('woff'),
       url(font-path('Chunkfive-webfont.ttf')) format('truetype'),
       url(font-path('Chunkfive-webfont.svg') + '#ChunkFiveRegular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

**Comment by scottdavis** [comment]
Are you using the latest alpha?

**Comment by agibralter** [comment]
Yup. Here is my Gemfile:

``` ruby
source 'http://rubygems.org'

gem 'rails',      '3.1.3'

# ...

gem 'haml',       '3.1.3'
gem 'compass',    '0.12.alpha.1'
gem 'oily_png',   '1.0.2'
gem 'chunky_png', '1.2.5'

group :assets do
  gem 'sass-rails',         '3.1.5'
  gem 'coffee-rails',       '3.1.1'
  gem 'jquery-rails',       '1.0.18'
  gem 'uglifier',           '1.1.0'
  gem 'compass-960-plugin', '0.10.4', require: 'ninesixty'
end

# ... test stuff
```

**Comment by scottdavis** [comment]
Put compass under sass-rails in the assets group

**Comment by agibralter** [comment]
Hmm still doesn't work -- I still get `wrong number of arguments (2 for 1) for font-url`

**Comment by agibralter** [comment]
And what's the point of compass's `font-url('foo', true)` method anyway when `sass-rails` provides `font-path`?

**Comment by agibralter** [comment]
This is what I was trying to do to get the `?#iefix` and `#ChunkFiveRegular` suffixes in the font urls with digests:

``` scss
@font-face {
  font-family: 'ChunkFiveRegular';
  src: font-url('Chunkfive-webfont.eot');
  src: url(font-url('Chunkfive-webfont.eot', true) + '?#iefix') format('embedded-opentype'),
       font-url('Chunkfive-webfont.woff') format('woff'),
       font-url('Chunkfive-webfont.ttf') format('truetype'),
       url(font-url('Chunkfive-webfont.svg', true) + '#ChunkFiveRegular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

It seems like my pure `sass-rails` approach works:

``` scss
@font-face {
  font-family: 'ChunkFiveRegular';
  src: url(font-path('Chunkfive-webfont.eot'));
  src: url(font-path('Chunkfive-webfont.eot') + '?#iefix') format('embedded-opentype'),
       url(font-path('Chunkfive-webfont.woff')) format('woff'),
       url(font-path('Chunkfive-webfont.ttf')) format('truetype'),
       url(font-path('Chunkfive-webfont.svg') + '#ChunkFiveRegular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

Is there a reason for compass to have `font-url` at all? Is it just for non-rails projects? Would it make sense to suppress these conflicting compass helpers in Rails 3.1+ projects?
