### ISSUE TITLE
Rails 3.1 and sprite-dimensions

### ISSUE THREAD

**Issue by andriusch** [Compass/compass#634]
Seems on newest alpha of compass (0.12.alpha.2) sprite-dimensions doesn't work anymore (it works on 0.12.alpha.0). Error looks like this:

TypeError: can't convert nil into String
/home/box2/.rvm/gems/ruby-1.9.3-p0/gems/compass-0.12.alpha.2/lib/compass/sass_extensions/functions/image_size.rb:17:in `extname'

I investigated this and seems that wrong image path is passed to Rails.application.assets.find_asset (eg. compass passes app/assets/image/icons/checked.png, while it should pass icons/checked.png.

On a bit unrelated note there seems to be a typo in image_dEmensions method name.

**Comment by scottdavis** [comment]
are you using sprockets?

**Comment by scottdavis** [comment]
Also the image_dimensions needs to get the full path to the file. im not sure why it would be passing anything to sprockets. It needs to ask sprockets where to find the file? maybe if i could see a gist of the sass causing the issue i can understand this a bit better.

**Comment by ghost** [comment]
Yes using sprockets. I don't have code right now, will post it tomorrow if I won't forget, but it's nothing fancy just creating sprite map with sprite-map and then asking for dimensions of one of the sprites using image-dimensions.

If you take a look at https://github.com/chriseppstein/compass/blob/master/lib/compass/app_integration/rails/actionpack31/helpers.rb#L13 this is where compass seems to ask Rails (sprockets) for full path to image, but this fails as compass passes path to image from rails root, while it should pass it with app/assets/images removed.

**Comment by scottdavis** [comment]
weird im not having this issue in my app using the new version and im using tons of sprites is it possibly an old version of sprockets?

**Comment by scottdavis** [comment]
https://github.com/chriseppstein/compass/blob/master/lib/compass/app_integration/rails/actionpack31/helpers.rb#L13

This function needs the full system path to the image so it can get the dimensions im not sure what you are saying? any update on this?

**Comment by andriusch** [comment]
I mean this: Rails.application.assets.find_asset(image_file), it needs path without app/assets/images. I'm using:
sprockets (2.0.3)
rails (3.1.3)
compass (0.12.alpha.2)

Here's code:

``` scss
$cbt-v-space: 20;
$cbt-h-space: 30;
$cbt-icons: sprite-map("cbt-icons/*.png",
    $cleanup: true,
    $checked-position: $cbt-h-space * 4, $checked-spacing: $cbt-v-space,
    $closed-position: $cbt-h-space * 3, $closed-spacing: $cbt-v-space,
    $open-position: $cbt-h-space * 2, $open-spacing: $cbt-v-space,
    $semi-checked-position: $cbt-h-space * 1, $semi-checked-spacing: $cbt-v-space,
    $unchecked-position: 0, $unchecked-spacing: $cbt-v-space
    );

span.choice-check-all {
    background: sprite($cbt-icons, 'unchecked', 3, 2) no-repeat;
    @include sprite-dimensions($cbt-icons, 'checked');
}
```
