### ISSUE TITLE
Optimize output of mixin inline-block

### ISSUE THREAD

**Issue by NoNoNo** [Compass/compass#641]
With Compass 0.11.5 && Sass 3.1.11 this SASS

``` SASS
A {
  @include inline-block;
}
```

is compiled to this CSS

``` CSS
A {
  display: -moz-inline-box;
  -moz-box-orient: vertical;
  display: inline-block;
  vertical-align: middle;
  *vertical-align: auto;
}
A {
  *display: inline;
}
```

I propose the output in only one rule:

``` CSS
A {
  *display: inline;
  display: -moz-inline-box;
  -moz-box-orient: vertical;
  display: inline-block;
  vertical-align: middle;
  *vertical-align: auto;
}
```

(And the authoritative ›display‹ declaration should be after the legacy / proprietary declarations)

Thanks & greetings!
