### ISSUE TITLE
Different image order for normal and retina sprites

### ISSUE THREAD

**Issue by thulstrup** [Compass/compass#690]
I have two folders of icons. One called "sprites" and one called "sprites-retina".
Both folders contains the same icons with the same filenames. The only difference is that the icons in the "sprites-retina" folder are double the size of those in the "sprites" folder.

When generating the sprite maps, the order of the icons in the "sprites" map is different than that of the "sprites-retina" map. This causes problems with the background-position of the retina icons.

I'm using the sprite-map function to generate the sprites.

``` css
$sprites: sprite-map("sprites/*.png");
$sprites-retina: sprite-map("sprites-retina/*.png");
```

**Comment by scottdavis** [comment]
let me see your sass

**Comment by thulstrup** [comment]
Here's the mixin I use to generate the normal and retina icons.

``` scss
$sprites: sprite-map("sprites/*.png");
$sprites-retina: sprite-map("sprites-retina/*.png");

@mixin sprite-background($name) {
  @include hide-text;
  background-image:sprite-url($sprites);
  background-position:sprite-position($sprites, $name);
  background-repeat:no-repeat;
  display:block;
  height:image-height(sprite-file($sprites, $name));
  width:image-width(sprite-file($sprites, $name));

  @media (-webkit-min-device-pixel-ratio: 2), (-o-min-device-pixel-ratio: 3/2), (min-device-pixel-ratio: 2) {
    // I was unable to get the dimensions of the sprites image, so I had to hard code it.
    @include background-size(444px auto);
    background-image:sprite-url($sprites-retina);
  }
}

// Usage.
.mail-icon {
  @include sprite-background(mail);
}
```

**Comment by scottdavis** [comment]
alright it seems there needs to be an option to define the sort order

**Comment by chriseppstein** [comment]
Sprite names are sorted alphabetically to determine sprite ordering to make the sprite construction stable across compiles.

I think it's incorrect to assume that the two sprites will have an identical placement. I suggest comparing the values of `sprite-position($sprites, $name)` and `sprite-position($sprites-retina, $name)` and outputing an override for `background-position` if they differ.

**Comment by thulstrup** [comment]
Thank you for your quick reply.
I've got it working, but it does seem a bit like a hack. Is this the best way to do it?

``` scss
@mixin sprite-background($name) {
  ...
  @media (-webkit-min-device-pixel-ratio: 2), (-o-min-device-pixel-ratio: 3/2), (min-device-pixel-ratio: 2) {
    @if (sprite-position($sprites, $name) != sprite-position($sprites-retina, $name)) {
      $xpos: round(nth(sprite-position($sprites-retina, $name), 1) / 2);
      $ypos: round(nth(sprite-position($sprites-retina, $name), 2) / 2);
      background-position: $xpos $ypos;
    }
    ...
  }
}
```

**Comment by scottdavis** [comment]
Sprites are actually sorted from top to bottom by file size then by name in vertical layout this is not true in horizontal layout:
https://github.com/chriseppstein/compass/blob/master/lib/compass/sass_extensions/sprites/layout_methods.rb#L44

**Comment by chriseppstein** [comment]
Doesn't seem hackish to me. If you want completely perfect sprite construction, you can hand build them ;) One of the main benefits of compass sprites is that you don't position them yourself and we do not make any guarantees around the assembly of them. So I think you're code is actually pretty optimal given the constraints.

**Comment by bmorrall** [comment]
@thulstrup I'm having the same Issue as you, and I ended up using your sprite-background mixin as a fix. However it has a bug, in that the if statement always evaluates to true. Here's a quick fix for that method:

``` SCSS
@mixin sprite-background($name) {
    ...
    @media (-webkit-min-device-pixel-ratio: 2), (-o-min-device-pixel-ratio: 3/2), (min-device-pixel-ratio: 2) {
        $xpos: round(nth(sprite-position($sprites-retina, $name), 1) / 2);
        $ypos: round(nth(sprite-position($sprites-retina, $name), 2) / 2);
        @if (nth(sprite-position($sprites, $name), 1) == $xpos and nth(sprite-position($sprites, $name), 2) == $ypos) {
            // Nothing to do here
        }
        @else {
            background-position: $xpos $ypos;
        }
    }
}
```
