### ISSUE TITLE
Unclear documentation of prefix helpers

### ISSUE THREAD

**Issue by Anahkiasen** [Compass/compass#767]
I'm trying to add prefixes to just one property but am unsure on how to do so. So I went and checked the documentation, unfortunately nothing explains the correct syntax for that. There is a link provided to [this page](https://github.com/chriseppstein/compass/blob/master/frameworks/compass/stylesheets/compass/css3/_images.scss) to take example, but it's actually not helping at all.
The sole example given use arrays of properties and all sort of unexplained functions, I can't begin to wrap my head around how to prefix one _single_ property.

EDIT : Nevermind, found I was actually looking for the experimental() function. Still, the documentation seems rather unclear to me, maybe this is open to discussion.

**Comment by chriseppstein** [comment]
Which property were you trying to prefix? I plan to make this much more configurable in the next release.

**Comment by Anahkiasen** [comment]
I was trying to prefix a _font-smoothing: antialiased_ wasn't sure of how to proceed. Now after looking at some mixins sources I understand that the function is actually called on the property name, which I didn't get at the time.

**Comment by jpcbarros** [comment]
How can I use the prefix!?

**Comment by silvenon** [comment]
``` scss
@import 'compass/css3/shared';

img {
  @include experimental(
    filter,
    grayscale(50%),

    $moz: false,
    $webkit: true,
    $o: false,
    $ms: false,
    $khtml: false,
    $official: true
  );
}
```

outputs:

``` css
img {
  -webkit-filter: grayscale(50%);
  filter: grayscale(50%);
}
```
