### ISSUE TITLE
Browser hacks module

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#787]
Now that we have `@content` a whole bunch of selector-based browser targeting hacks can be created.

@paulirish wrote an excellent blog post [enumerating them](http://paulirish.com/2009/browser-specific-css-hacks/)

I wish hacks weren't necessary, but I still need them from time-to-time.

**Comment by paulirish** [comment]
there are really only like 3 (maybe 5) that can safely be used, IMO. 
more at http://mathiasbynens.be/notes/safe-css-hacks

**Comment by neekey** [comment]
want this feature too. Maybe we can use hack module like:

``` scss

@include hack( ie6 ){
    background: red;
}

// Will output
_background: red;

```
