### ISSUE TITLE
Add support for -webkit-filter: grayscale

### ISSUE THREAD

**Issue by ghost** [Compass/compass#811]
I'm using <a href="https://dvcs.w3.org/hg/FXTF/raw-file/tip/filters/index.html#ShorthandEquivalents">Webkit Filters</a>, and Compass isn't agreeing with <code>-webkit-filter:grayscale(100%); </code>. 
I'm using 100% for the example, but it won't take any number. 

The error I'm getting is <code>100% is not a color for 'grayscale'</code>. 

Other filter effects work fine. 

Compass 0.12.rc.1 (Alnilam)

**Comment by jonjaques** [comment]
This will work for now.

``` scss
$percent: 100%;
-webkit-filter: unquote('grayscale(#{$percent})');
```

You could inline the value too.
