### ISSUE TITLE
vertical-rhythm module should allow for true relative font sizing

### ISSUE THREAD

**Issue by mirisuzanne** [Compass/compass#843]
The current master branch version of `establish-baseline` works as follows:

``` scss
// input
@include establish-baseline(14px); 

// output
* html {
  font-size: 87.5%; }

html {
  font-size: 14px;
  line-height: 1.143em; }
```

The percentage-based output is hidden behind a hack, so it is only seen by IE6/7. All other browsers get a font-size set in px. While that seems to be accepted practice, it breaks the ability for browser users to set their own default font size. This becomes even more important with media-queries, where the only value of "em" that is recognized comes directly from that browser default setting. The only way to create a meaningful em-based media-query is to know the relative value of your own ems. The only way to know that is by setting the one in relation to the other.
