### ISSUE TITLE
users should be able to override default browser-support in compass css3 mixins

### ISSUE THREAD

**Issue by mirisuzanne** [Compass/compass#850]
I think the best solution in this case is the compromise: `$default-browser-support` settings for each css3 module that you can easily override as a user. I see this best accomplished with a list variable at the top of each css3 module:

``` scss
// Initial support matrix would be maintained as part of compass
$border-radius-support: -moz, -webkit, not -o, not -ms, -khtml, official !default;

.default {
  @include border-radius(3em);
}

// .default {
//      -moz-border-radius: 3em;
//   -webkit-border-radius: 3em;
//    -khtml-border-radius: 3em;
//           border-radius: 3em; 
// }

// A user could override that support matrix at any time.
$border-radius-support: -moz, -webkit, not -o, not -ms, not -khtml, official;

.override {
  @include border-radius(6em)
}

// .override {
//      -moz-border-radius: 6em;
//   -webkit-border-radius: 6em;
//           border-radius: 6em; 
// }
```

This solution would allow advanced users to manage their own support matrix, while allowing beginners to lean on the defaults. It also gives us a very clear and simple way to update browser support quickly in the compass core, making it very easy for anyone to submit a patch at any time.

I'm not sure how difficult that is to implement at this point, with list functions as they stand. I imagine it would take some work, or some help from sass. This has been discussed some in #535.

**Comment by mirisuzanne** [comment]
I added this feature to border-radius in 50704cecfc. Unless someone sees a better approach, I'll start pulling that same solution into all the CSS3 modules, and add it to the changelog.

**Comment by chriseppstein** [comment]
I do not like this feature, at least not how it's implemented here. The problem is that once they set this, we can no longer do our job to know which features should be enabled and which should be disabled -- they've locked themselves into using their own knowledge of support and at that point they really should just make their own mixin -- it would far simpler than knowing to set this variable.

**Comment by mirisuzanne** [comment]
I see. While it allows the user to take control in the immediate case, that means we lose control down the road. Hmmm. I think there is a real problem here that needs to be addressed - our ability to keep up with browser changes as they come out. 

Maybe the solution isn't user control, but a simpler way to update the support matrix? In that case, I think this basic approach is still the DRY way to go internally - we would just want to keep it private. If there is a single variable that needs to be changed with any given browser update, does that help us keep on top of changes fast enough for our users?

**Comment by mirisuzanne** [comment]
d87686891 makes this setting private.

Is there any approach to user-control of browser-support that we want to pursue, or are we dropping this issue? If I continue simplifying these CSS3 modules, we should be able to make these changes quickly, or ask people to submit simple patches - getting a faster turn-around time. Is that a solution?

**Comment by chriseppstein** [comment]
Yes. I think simple changes and rapid releases from stable is the right approach. 

In an ideal world, we have tests that tell us when caniuse says something is supported but it's not in our framework.

**Comment by tbredin** [comment]
Hrmmmm I've run into similar browser support issue (well, removing support, rather) - where I don't think I'm currently able to set the "official" support variable on a global scope or even at a per-CSS3-mixin level, however I do think something like Eric's original solution could solve this.. perhaps a variable called $global-browser-support that you could set before the relevant mixins (and reset afterwards if applicable) that takes similar values to your $border-radius-support?

The use case I have is a legacy stylesheet for IE8 and below that drops vendor prefixes (and susy grid media output). However, I feel that for these browsers we could take it a step further and almost set a global "$support-for-official" to false since these browsers have little to no css3 support for most of compass's css3 mixins anyway - but are still receiving a lot of redundant rules. 

Currently a static value of "true" in the experimental mixin doesn't seem that useful at all when we're calling it from within css3 mixins, or have I missed something?

**Comment by mirisuzanne** [comment]
That doesn't make sense to me. "Official" is not something you can turn on and off, because it's not actually a unique thing: it's just CSS. You're basically asking for a trigger to turn off CSS output. With a simple on/off like that, there is no way for Compass to know which properties you want supported and which you don't. Turn off all official css output from Compass? Just from the Compass css3 module? The distinction is arbitrary, because it's not based on actual support of any actual features.

**Comment by tbredin** [comment]
Yeah, I see what you mean. Something like your original solution probably is better in this context, on a per-mixin basis makes a lot more sense than globally, haha.

However I can still think of a lot of instances where you might wish to turn off raw css output (official) for a given mixin while keeping some of the vendor prefixed output (or indeed for the case of multiple output files from a single source I definitely have some I want to turn off completely for certain stylesheet outputs)

My only other suggestion (just throwing out ideas here) would be that maybe we could pass an override for the support matrix as an argument for the mixin.. 

``` scss
$my-support-matrix-variable:  -moz, -webkit, not -o, not -ms, not -khtml, not official;

.override {
    @include border-radius(4em, $my-support-matrix-variable);
}

//webkit and mozilla browsers only
// .override {
//      -moz-border-radius: 6em;
//   -webkit-border-radius: 6em;
// }

```

For example.
This way we could change the value of $my-support-matrix-variable depending on the output we're targeting (legacy/modern) and only pass it as an argument where it's needed to affect a certain output. And of course you could just declare separate variables for each of the compass CSS3 modules you want to affect if that's what you need.

Just another idea, not sure it's quite what we'd want either, thoughts?

**Comment by mirisuzanne** [comment]
We are building things according to my original proposal, but marking the variables as private. I think @chriseppstein is right that we don't want to encourage people messing with the support variables locally, but if you are willing to dig for it, the variable is there, and you can change it at your own risk.

This has already been implemented in most of the CSS3 modules on the master branch (and 0.13.alpha.2 gem).

**Comment by tbredin** [comment]
Oh it has? Excellent! 

I think this will address the issue I had originally (to be clear: it's not a huge redundancy saving anyways - nevertheless it is still a measurable improvement). I will do some digging! 

Thanks Eric, keep up the good work!

**Comment by tbredin** [comment]
Is it not deemed worthwhile including support for removing the output for the official spec? 

Had a dig in master and noticed you've trimmed down the matrix to 5 places that doesn't include "official" :( - So my original issue still exists

**Comment by mirisuzanne** [comment]
Oh, you're right. But yes, I don't see much reason to consider `official` part of any support matrix. Your use case is part of a much bigger issue. Making the change here would add complexity at the wrong place, without actually solving the problem correctly. What you should do instead (if you really think this is a problem worth the wasted effort) is create your own support variable/mixin to use with any properties you want:

$ie-only: false;

@mixin no-ie() {
 @if not $ie-only { @content; }
}

@include no-ie {
  // any properties in here will appear/disappear based on the $ie-only setting.
}

That gives you complete control over what css values should or should not be hidden from IE, without us adding complexity to what should be simple support variables.

**Comment by mirisuzanne** [comment]
All browser support has moved into the new variables, so I'm closing this story.

**Comment by cimmanon** [comment]
@tbredin I don't see the problem here?  Unless I've missed something, the behavior of the experimental mixin already seems to do what you want.  It doesn't matter if the list has 5 or 6 values because the argument defaults kick in when you have less than 6.

``` scss
$x-support: -webkit, -moz, -ms, -o, -khtml;

.foo {
    @include experimental(foo, bar, $x-support...);
}

$x-support: append($x-support, not standard);

.bar {
    @include experimental(bar, foo, $x-support...);
}
```

``` css
.foo {
  -webkit-foo: bar;
  -moz-foo: bar;
  -ms-foo: bar;
  -o-foo: bar;
  foo: bar;
}

.bar {
  -webkit-bar: foo;
  -moz-bar: foo;
  -ms-bar: foo;
  -o-bar: foo;
}
```
