### ISSUE TITLE
reset now conflicts with establish-baseline

### ISSUE THREAD

**Issue by mirisuzanne** [Compass/compass#859]
establish-baseline was changed in 48bfe186 to assign the base-font settings to the HTML element rather than the body element. That was a good choice overall, but it creates a conflict with the compass reset:

``` css
/* from reset */
body {
  line-height: 1;
}

/* from establish-baseline */
html {
  font-size: 14px; 
  line-height: 1.143em; 
}
```

The reset line-height assigned to `body` will override the authors line-height on `html` because it has higher specificity in the cascade. That's a problem.

cc/ @JohnAlbin
