### ISSUE TITLE
Including a file twice changes the output of multiple selectors

### ISSUE THREAD

**Issue by StanAngeloff** [Compass/compass#869]
The following code listing produces unexpected output:

``` ruby
# config.rb

css_dir    = ''
sass_dir   = ''
images_dir = ''
relative_assets = true
line_comments   = false
environment     = :development
output_style    = :nested
```

``` scss
// _forms.scss

form {
  input,
  select {
    color: white;
  }
}
```

``` scss
// style.scss

@import "forms";
@import "forms";
```

When `compass compile --force` is used in the terminal, the following file is generated:

``` css
/* style.css */

form input,
form select {
  color: white; }

form input, form select {
  color: white; }
```

This comes up when a file is included from multiple sources as well. I've noticed it because when I use `compass compile --force` to re-compile all assets, some files end up with selectors on a single line. When I use `compass watch` those selectors are formatted properly on separate lines. This is likely because `watch` compiles only affected files, thus includes from multiple sources do no occur. `compile --force` on the other hand does all files.

The behaviour is inconsistent and very inconvenient as it generated constants changes in files.

I haven't been able to trace it in code.
