### ISSUE TITLE
IE10 will support text-shadow spread, just like box-shadow

### ISSUE THREAD

**Issue by heygrady** [Compass/compass#870]
http://blogs.msdn.com/b/ie/archive/2011/09/29/css3-text-shadow-in-ie10.aspx

Here's the example pulled from their blog article. The text-shadow mixin is going to need to be updated to support this, or it would be nice if it was.

``` css
.shadow7 {
  color: black;
  text-shadow: #99FFCC 0px 0px 10px; /* for browsers without spread distance */
  text-shadow: #99FFCC 0px 0px 10px 10px; /* for browsers with the full spec */
}
```

Ideally the text-shadow mixin would just drop the spread parameter for the unsupported browsers.

``` scss
.shadow7 {
  color: black;
  @include text-shadow( #99FFCC 0px 0px 10px 10px );
}
```

Firefox has been considering adding this for over a year. https://bugzilla.mozilla.org/show_bug.cgi?id=655590
