### ISSUE TITLE
remove -ms- prefixes for particular IE10 features

### ISSUE THREAD

**Issue by paulirish** [Compass/compass#924]
based on http://blogs.msdn.com/b/ie/archive/2012/06/06/moving-the-stable-web-forward-in-ie10-release-preview.aspx

we don't need ms prefixes on transitions, gradients, or keyframe animations.  let's strip them out.

**Comment by alanhogan** [comment]
Nice :)

I absolutely love that Compass users have these decisions made for them for free. +1

**Comment by alanhogan** [comment]
Also, big ups to MS for helping battle excessive prefixing here.

**Comment by chriseppstein** [comment]
@paulirish Was there never a shipped version of IE that had these prefixed then?

**Comment by paulirish** [comment]
> Was there never a shipped version of IE that had these prefixed then?

Nope. Just IE10 platform previews.

IE9 has prefixed transforms (and IE10 will not) so we're stuck with `-ms-transform` for a while

**Comment by chriseppstein** [comment]
Fixed. Thanks for the heads up!

**Comment by salimhb** [comment]
For people who might be puzzled when linear-gradient doesn't work in IE10 in some cases without adding the -ms prefix, read this: http://joshuapaling.com/post/compass-background-gradients-not-working-ie10

**Comment by vote539** [comment]
I use Compass to simplify my coding process on faith that it is covering all important edge cases.  However, after going to my newest site on a friend's PC, I discovered that the background gradients are completely messed up in IE 10.

Do you think we can reverse this commit and add the -ms- prefix back into Compass gradients?  The -ms- browser prefix increases the weight of CSS no more than the -o- browser prefix, and yet it reaches a much larger audience.

**Comment by salimhb** [comment]
@vote539 there's no need for the ms- prefix, check the link I posted in my previous comment.

**Comment by vote539** [comment]
I read your link yesterday.  What I'm saying here is something different.

I understand that the objective of Compass is to ease development by making CSS statements cross-browser-compatible when possible.  The fact that I can write a SASS `linear-gradient` statement that works in WebKit and Gecko but not IE 10, despite the fact that the documentation for that function claims to support IE 10, is a problem.

If I had not used Compass in my project and instead used one of the CSS gradient generators available online, my site would have worked in IE 10 from the start.  That's also a problem.

I think it's great that IE 10 supports the W3C standard `linear-gradient` without a prefix.  However, Compass should either always output `linear-gradient` statements that are compatible with IE, or it should output the `-ms-` prefix to increase compatibility.

**Comment by salimhb** [comment]
In my case, Solution 1 from that link worked, but Solution 4 seems to cover all cases, have you tried it?
The thing is that the problem here is about the parameters passed to linear-gradient, not the support for linear-gradient itself.

**Comment by vote539** [comment]
My site uses a limited number of left-to-write gradients, so Solution 1 won't work for me.  I ended up using Solution 3.  But that's not my point.  I can always find workarounds.  If Compass is supposed to make my life easier, it should prevent me from ever needing to read that article.

**Comment by cimmanon** [comment]
@vote539 Do you have any information to backup your claims?  [Caniuse reports IE10 as being prefix free and having "complete support"](http://caniuse.com/#feat=css-gradients) (which means that it supports all features found in the current W3C specification).  Compass (as of 1.0) decides which prefixes are valid based on information provided by Caniuse, this information is not coded by hand like it was in 0.12 and older.

**Comment by salimhb** [comment]
@vote539 I agree, I don't like Solution 3 either, have you tried Solution 4 using `90deg` for the gradient direction?
so it would be: `@include background-image(linear-gradient(90deg,  ...))`

**Comment by vote539** [comment]
Here's the code I was using.

```
@include background-image(linear-gradient(left, $color1 40%, $color2 50%));
```

Try it.  It works in WebKit and Gecko, but not in IE 10.

Sure, if I read the article salimhb posted, I can change my code to make it work in IE 10.  That's not my point.  If Compass is trying to make my life easier, it should either complain if I try using the `left` keyword instead of the `90deg` keyword, or it should deal with the problem some other way like by adding a line with a `-ms-` prefix.  :smiley:

**Comment by salimhb** [comment]
@vote539 as the link says: "I noticed it wasn’t working in IE 10, and on further investigation, the problem is actually that IE 10 is going by the WC3 standards (Gasp!) and Compass (following the implementation in other browsers) isn’t."

If you go to the [W3C page](http://dev.w3.org/csswg/css-images-3/#linear-gradients), you will see that `left` as a direction is not standard, you can use `[ <angle> | to <side-or-corner> ]`. So `left` is not standard, `to right` is correct, or the `XXdeg` keyword. Compass should not take care of converting `left` to `to right`, that's too much magic, you should take care of using the correct standard values. And these generators around the web should be doing that too.

**Comment by chriseppstein** [comment]
In compass 1.0:

``` sass
.bg-linear-gradient-pixel-stop-from-top
  +background-image(linear-gradient(top, #ddd 10px, #aaa 40px))
```

produces:

``` css
.bg-linear-gradient-pixel-stop-from-top {
  background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4gPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkIiBncmFkaWVudFVuaXRzPSJvYmplY3RCb3VuZGluZ0JveCIgeDE9IjAuNSIgeTE9IjAuMCIgeDI9IjAuNSIgeTI9IjEuMCI+PHN0b3Agb2Zmc2V0PSIyNSUiIHN0b3AtY29sb3I9IiNkZGRkZGQiLz48c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNhYWFhYWEiLz48L2xpbmVhckdyYWRpZW50PjwvZGVmcz48cmVjdCB4PSIwIiB5PSIwIiB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ1cmwoI2dyYWQpIiAvPjwvc3ZnPiA=');
  background-size: 100%;
  background-image: -moz-linear-gradient(top, #dddddd 10px, #aaaaaa 40px);
  background-image: -webkit-linear-gradient(top, #dddddd 10px, #aaaaaa 40px);
  background-image: linear-gradient(to bottom, #dddddd 10px, #aaaaaa 40px); }
```

so the old syntax is converted to the new standard and works great in IE 10.

**Comment by vote539** [comment]
### Using Legacy "left" Syntax

Compass version 0.12.7

``` scss
// app.scss
@import "compass";

$color1: red;
$color2: orange;

.example{
        @include background-image(linear-gradient(left, $color1 40%, $color2 50%));
}
```

``` bash
$ compass compile
overwrite stylesheets/app.css
```

``` css
/* app.css */
.example {
  background-image: -webkit-gradient(linear, 0% 50%, 100% 50%, color-stop(40%, #ff0000), color-stop(50%, #ffa500));
  background-image: -webkit-linear-gradient(left, #ff0000 40%, #ffa500 50%);
  background-image: -moz-linear-gradient(left, #ff0000 40%, #ffa500 50%);
  background-image: -o-linear-gradient(left, #ff0000 40%, #ffa500 50%);
  background-image: linear-gradient(left, #ff0000 40%, #ffa500 50%);
}
```

Firefox 30:
![firefox](https://cloud.githubusercontent.com/assets/2059203/3631903/ba9de200-0ebc-11e4-92b7-c68cb7b735fd.png)

IE 11:
![ie-broken](https://cloud.githubusercontent.com/assets/2059203/3631904/ba9f38bc-0ebc-11e4-89dc-b0c9d4dd4f1c.png)

Safari 5.1 for Windows:
![safari](https://cloud.githubusercontent.com/assets/2059203/3632083/c53a2db0-0ebf-11e4-83f6-c8a7b7a2e35e.png)

---

### Using W3C "to right" Syntax

Compass version 0.12.7

``` scss
// app.scss
@import "compass";

$color1: red;
$color2: orange;

.example{
        @include background-image(linear-gradient(to right, $color1 40%, $color2 50%));
}
```

``` bash
$ compass compile
Cannot determine the opposite position of: to
overwrite stylesheets/app.css
```

``` css
/* app.css */
.example {
  background-image: -webkit-gradient(linear, to right, to left, color-stop(40%, #ff0000), color-stop(50%, #ffa500));
  background-image: -webkit-linear-gradient(to right, #ff0000 40%, #ffa500 50%);
  background-image: -moz-linear-gradient(to right, #ff0000 40%, #ffa500 50%);
  background-image: -o-linear-gradient(to right, #ff0000 40%, #ffa500 50%);
  background-image: linear-gradient(to right, #ff0000 40%, #ffa500 50%);
}
```

Firefox 30:
![firefox](https://cloud.githubusercontent.com/assets/2059203/3631903/ba9de200-0ebc-11e4-92b7-c68cb7b735fd.png)

IE 11:
![ie](https://cloud.githubusercontent.com/assets/2059203/3632092/f4cd6d08-0ebf-11e4-8ffd-57754c1bd1e8.png)

Safari 5.1 for Windows:
![safari-broken](https://cloud.githubusercontent.com/assets/2059203/3632094/fcdae9c6-0ebf-11e4-9a61-9b2688647030.png)

---

In other words, if I use the legacy syntax, the gradient does not work in IE 11.  But if I use the W3C standard syntax, the gradient does not work in an old version of Safari.  For what it's worth, when I use the `90deg` syntax, Firefox 30 and IE 11 work but Safari 5.1 renders the gradient in the vertical direction.

Since @chriseppstein shows that Compass 1.0 will convert `top` into `to bottom`, and presumably `left` into `to right`, then that's the best solution that will solve this issue for all browsers.  However, the problem remains for version 0.12.7, which is the current stable.
