### ISSUE TITLE
Blueprint: showgrid for liquid layouts

### ISSUE THREAD

**Issue by mdesantis** [Compass/compass#926]
Hello,

I am writing a site with blueprint using its liquid layout, but the default showgrid is just for fixed layouts; so after some tries I managed to write a mixin which implements a showgrid for liquid layout:

``` scss
@mixin liquid-showgrid($image: false) {
  @if $image {
    background: image-url($image);
  }
  @else {
    @include grid-background(
      $total    : $blueprint-liquid-grid-columns,
      $column   : $blueprint-liquid-grid-width,
      $gutter   : $blueprint-liquid-grid-margin,
      $baseline : $blueprint-font-size * 1.5,
      $offset   : 0%
    );
  }
}
```

It is the showgrid mixin modified: it uses the liquid layout variables and a percentual value for the offset (it gives an error if the offset has not a percentual value). It works with compass 0.12.1.

Maybe the image argument has not sense, because the layout is liquid.

The offset value should be setted to a default variable too, in my opinion (maybe `$blueprint-liquid-grid-offset`?)

If it can be something that can be itegrated into blueprint I could open a pull request (or if someone wants to integrate it at my place, no problem; I don't know if you accept pull requests).
