### ISSUE TITLE
Compass and older webkit transition syntax

### ISSUE THREAD

**Issue by Anahkiasen** [Compass/compass#942]
I'm using Compass 0.13.alpha.206cf46, I wanted to do a simple transition on a form outline :

``` sass
input
    +transition(border linear .2s, box-shadow linear .2s)
```

But then in the output I found the following :

``` css
input {
  -webkit-transition: border linear, box-shadow linear;
  -webkit-transition-delay: 0.2s, 0.2s;
  -moz-transition: border linear 0.2s, box-shadow linear 0.2s;
  -ms-transition: border linear 0.2s, box-shadow linear 0.2s;
  -o-transition: border linear 0.2s, box-shadow linear 0.2s;
  transition: border linear 0.2s, box-shadow linear 0.2s;
}
```

The problem as you can see is that the -webkit syntax differs from the other one. In itself it's not a problem, but the issue is that Chrome 21 reads the -webkit transition (or part of it) instead of the normal unprefixed transition property. I don't know exactly what it gathers from the whole bloc but the transition doesn't work.

Is there a compatibility variable to set to false or something ?
