### ISSUE TITLE
Vertical Rhythm is Off

### ISSUE THREAD

**Issue by nsteffan** [Compass/compass#955]
I took a look at the issue here:
https://github.com/chriseppstein/compass/issues/806

I believe the original issue submitter is correct.

When I do:
<code>
h1 {
  @include adjust-font-size-to($base-font-size \* 3);
}
</code>

I get:
<code>
h1 {
  font-size: 3em;
  line-height: 3.375em;
}
</code>

What that is actually saying is the font-size is 3 times that of the base font size (16px). By specifying a line-height of 3.375em, you are actually creating a line-height of (16px x 3 x 3.375) 162 px. That is not right at all.

When I get a chance, I will see about creating a patch. Thanks.

Sources:
http://www.w3schools.com/cssref/css_units.asp
http://www.w3schools.com/cssref/pr_dim_line-height.asp

**Comment by nsteffan** [comment]
One thing I determined was the configuration and import of the vertical rhythm file matter:

This properly sets the vertical rhythm up.

<code>
@import "compass/reset";

// Font Sizes
$relative-font-sizing : false;
$base-font-size       : 16px;
$base-line-height     : 18px;
$round-to-nearest-half-line : true;

@import "vertical_rhythm";

// establish your vertical baseline grid.
@include establish-baseline;

h1 {
    @include adjust-font-size-to(48px);
}

p {
    &:first-child {
      @include leader;  
    }
    @include trailer;
}
</code> 

This doesn't:
<code>

@import "compass/reset";
@import "vertical_rhythm"; // Local Copy of Vertical Rhythm

// Font Sizes
$relative-font-sizing : false;
$base-font-size       : 16px;
$base-line-height     : 18px;
$round-to-nearest-half-line : true;

// establish your vertical baseline grid.
@include establish-baseline;

h1 {
    @include adjust-font-size-to(48px);
}

p {
    &:first-child {
      @include leader;  
    }
    @include trailer;
}
</code>

**Comment by chriseppstein** [comment]
@snugug @johnalbin Thoughts?

**Comment by Snugug** [comment]
@chriseppstein Yah, he's right about the line height in ems thing, what can I do to help? Would we prefer to do the em calculation and spit out what we want from rems too (which is what's actually being calculated w/the line height) or just ems? Personally, I don't think we need to spit out the rems if we're calculating the real ems.

Also, I haven't looked at the code, but if Vertical Rhythm is making calculations w/o being wrapped with a mixin, then it's going to use the !default instead of the variables the user sets; it's this same reason why I've been including a "kickstart" mixin for all of my extensions that need to do initialization calculations, allowing the user to import wherever they'd like and simply call the "kickstarter" when they're ready to start using.

**Comment by nsteffan** [comment]
I think doing something similar to a bootstrap or kickstart mixin may be the proper way to approach this, or possibly include the functionality inside the establish-baseline mixin as anyone using the vertical rhythm plugin will probably be making this call. Another option would be to create the mixin outside of the establish-baseline mixin, but then have the establish-baseline mixin call the bootstrap/kickstart mixin.

**Comment by mdeltito** [comment]
I'm seeing a similar result:
https://gist.github.com/3249043

Note that I'm not setting relative-font-sizing to false

I expected the output to properly adjust both the font-size and line-height down to the proper value to maintain the rhythm. Instead like the example from nsteffan above I'm seeing the line-height adjusted to match the baseline px value.  

I'm not well-versed in working with vertical rhythm in general, so it's very possible I'm doing something wrong. If this is in fact an issue (or just the way it works) is there another method I should be used to properly adjust line-height along with font-size whilst maintaining the rhythm?

**Comment by mirisuzanne** [comment]
I can't recreate the first part of this. When I input:

``` scss
h1 { @include adjust-font-size-to($base-font-size * 3); }
```

I get this output:

``` scss
h1 {
  font-size: 3em;
  line-height: 1.33333em;
}
```

That's correct.

**Comment by mirisuzanne** [comment]
The Compass tests are also providing correct results:

``` scss
// in
$base-font-size: 14px;
$base-line-height: 16px;
.small { @include adjust-font-size-to(12px,1); }

// out
.small {
  font-size: 0.857em;
  line-height: 1.333em; }
```

**Comment by nsteffan** [comment]
Ericam, my issue stems from when $relative-font-sizing : false is set. Please look at my second comment for a reproducible issue.

**Comment by mirisuzanne** [comment]
I see. It's all one issue, easily solved by a kickstart:

``` scss
@mixin kickstart {
  $font-unit: if($relative-font-sizing, 1em, $base-font-size);
  $base-rhythm-unit: $base-line-height / $base-font-size * $font-unit;
  $base-leader: ($base-line-height - $base-font-size) * $font-unit / $base-font-size;
  $base-half-leader: $base-leader / 2;
}
```

Which can be called by establish-baseline, as mentioned. 

However, much of this is changing in #896 anyway. I wonder if we can completely remove the need for calculations outside mixins/functions? That always seems like the safest route to me.
