### ISSUE TITLE
compass sprite generating bad comment syntax

### ISSUE THREAD

**Issue by ventrebleu** [Compass/compass#995]
Hi and thanks for the awesomeness!

Little bug report : using the sprite feature with nested folders and being in the development output mode for compilation cause a css error cause it outputs something in comments like this:

/\* line 226, nav/*_/_.png */

and of course the comment tag is wrong.

**Comment by silvenon** [comment]
Wow, nice catch! :)

**Comment by silvenon** [comment]
Hmm, I tried reproducing this, but the issue seems to be resolved. The slashes are escaped in my output:

``` css
/* line 58, icons/**\/*.png */
.icons-sprite, .icons-one, .icons-two, .icons-three {
  background: url('../images/icons-sfd064a7e8a.png') no-repeat;
}
```

Update Compass, try it again and see if the problem persists.
